### ISSUE TITLE
log verbosity; log noise: "replication status: Disconnected"

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#220]
Every other second master logs message like the following to syslog:

~~~~
mfsmaster[1685]: (192.168.0.250:9422) chunk: 00000000001D1CA6 replication status: Disconnected
~~~~
with IP addresses from all chunkservers. Is this a normal mode of operation of is this a problem? It it is normal then perhaps those messages can be suppressed? 
How to control log verbosity?
For example I'd also like to suppress `mfschunkserver[29638]: testing chunk` messages unless there is a problem like CRC error... 
Please advise.

**Comment by marcinsulikowski** [comment]
`testing chunk ...` messages are no longer generated (https://github.com/lizardfs/lizardfs/commit/5a71d97b2bab6f702e578f353aef95e94b3c7e18).

**Comment by onlyjob** [comment]
So how can one monitor background scrubbing now? Indeed those messages are not useful _by default_ but it still may be good to enable 'em in "debug" mode...

**Comment by marcinsulikowski** [comment]
What do you mean by "monitor background scrubbing"? There are many background tasks done in LizardFS which just silently do their work. This message annoyed a lot of people and some MooseFS maintainers in the past were removing it when building packages (as far I as remember this happened in FreeBSD ports). Moreover, if you use chunkservers which use RAIDs instead of JBOD, you might want to set the frequency to 1 chunk per second, which generates a huge amount of such logs...

If you think that is useful, we can add some alternative message though, e.g. some summary with number of tested chunks and processed megabytes every hour or so.

**Comment by onlyjob** [comment]
By "background scrubbing" I meant verifying chunk's integrity.

Marcin, I fully support takedown of this message. It is harmful in production where it is polluting logs. Nobody needs to know every N seconds when yet another chunk is tested unless there are errors. If I have to release 2.5.4.2 to Debian most probably I will remove this message as well.

However I think that this sort of diagnostic messages may be still useful to output when chunkserver is started with `--debug` argument. I like the idea to log hourly integrity check summary even more -- please implement it so admins would have at least some evidence that background integrity check is working. Thanks.

**Comment by Zorlin** [comment]
Agree fully with both of you ;) Having a summary that says something nice
and reassuring like "Scanned XXXXX chunks, all passed integrity checks"
each hour would be wonderful, and low-noise. Having that positive feedback
from a bunch of my chunkservers via my ELK stack would be awesome.

~ b

**Comment by borkd** [comment]
While troubleshooting #222 I have changed goal for two files in an already fully replicated 4TB dataset for which snapshots exist (no over and undergoal chunks reported before goal change). As replication and rebalance started "mfsmaster[###]: (###) chunk: XXX replication status: Disconnected" messages started showing up periodically in the mfsmaster log and the numbers of undergoal chunks in info and chunks tabs started to diverge (compare the summary numbers in the screenshot below).

![lizardfs undergoal discrepancy](https://cloud.githubusercontent.com/assets/12971584/8270557/d6966ce4-17b1-11e5-9593-c47ce38ecd3a.png)

To help replicate, and eventually make a test case for this issue, the mfsmaster uses default settings except for 30min replication delay. Network traffic was marginal compared to typical load. Replication is still ongoing.

**Comment by borkd** [comment]
@psarna - I have done a thorough review of my chunkservers. Except for one catastrophic disk failure and associated chunkserver hang/power cycle and one instance of packet loss between datacenters there were no other malfunctions or instability. Catastrophic and silent storage faults, chances of packet loss/partitions are to be expected periodically in any distributed deployment, and LizardFS behaved surprisingly well in those instances so far.

Is there a way to safely adjust the thresholds used in replication by a parameter exposed in config file and check whether the issue goes away? Disconnected messages seem to coincide with occasional higher read/write times, which are a norm rather than exception for my installation. With target number of files in hundreds of millions having this as a tunable seems to make sense.

A significant portion of data we use compresses well (1.3x to 4x), and we also have zillions of small files. ZFS has been used on legacy systems, so chunkservers for certain goals use ZFS with lz4 compression as well. I'm speculating that even with plenty of cores and reasonable ARC/L2ARC response times of underlying rust may periodically cross into the replication timeout range. SLOGs help, but don't  completely eliminate periodic spikes in response times.

**Comment by psarna** [comment]
Adjusting replication parameters was discussed in https://github.com/lizardfs/lizardfs/issues/255.
Also, a batch of fresh options is going through review: http://cr.skytechnology.pl:8081/#/c/1979/

Finally, in the near future you can expect to see commits that give you more freedom in tuning up chunkservers.

**Comment by psarna** [comment]
Newly merged commits:
https://github.com/lizardfs/lizardfs/commit/6ccfdf8b6aa8299857b167c7dd2d49bf4f1a6d51
https://github.com/lizardfs/lizardfs/commit/f102e9f790f601c06ff84f255dd8c14ef65a7a2f

Added/amended options are:
~~~
*CHUNKS_LOOP_MIN_TIME*::
Chunks loop will check all chunks in specified time (default is 300) unless *CHUNKS_LOOP_MAX_CPS*
will force slower execution.

*CHUNKS_LOOP_PERIOD*::
Time in milliseconds between chunks loop execution (default is 1000).

*CHUNKS_LOOP_MAX_CPU*::
Hard limit on CPU usage by chunks loop (percentage value, default is 60).
~~~

Please let me know if it helped (it should). If the problem persists, I will reopen the issue.
