### ISSUE TITLE
Obey (minimum) goal settings

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#227]
Even with _goal=2_ LizardFS client happily (acknowledge) writes to only one chunkserver (with only one HDD)... That is the only one (degraded) chunk is created where goal requires to make at least two. Therefore data is endangered right away since the moment it is written because goal is not enforced.

Ceph have goal and _minimum goal_ settings. For example when goal=3 and minimum_goal=2 ceph client acknowledge writes only when at least two replicas of data are written successfully to different storage servers. This allows to operate partially degraded cluster safely.

I strongly recommend to either enforce goal setting _hard_ or introduce additional _minimum goal_ setting to define minimum acceptable number of replicas created on write. Client should treat situation when less than minimal number of chunkservers is available as if there were no chunkservers at all and hold all writes until minimal goal can be satisfied.

Besides current implementation do not strike me as safe: what if client acknowledge write after one chunk successfully created on chunkserver which fails before another replica is made? Data loss I presume... :(

**Comment by 4Dolio** [comment]
I'm curious if perhaps the opposite of this features desired outcom might have it's own applications?
Perhaps while keeping with the existing goal=3 and by changing the proposed minimum_goal=2 to something like initial_goal=2 or satisfied_goal=2 or write_goal=2.  Taken this new options value literally as the number of replicas to be written regardless of the goal in order to report success to the client.  Put another way the value of this option would become the number of replicas which the client will write in order to be considered successful. You could then also enforce that only 1 replica be written (Presuming that a chunks revision value gets incremented upon writes and out of date replicas become invalid and in need of lazy replication).

With a value of 2+ the desired minimum 2 replicas written would occur.  With a value of 1 however only one replica would be required (The other revisions would become invalid and rely on replication to bring them back into sync).  I imagine that this might increase performance, at the expense of risking dataloss.  However, if leverages along with topologies and custom goal labels it could make high latency links less of an issue when some of the replicas on distant chunkservers are likely to cause delays in write completion.

Imagine I have CS1&2 at siteA and CS3&4 at SiteB.
Goal=4 (Or a custom goal = 2@SiteA for branches of the dataset which live there & 1@SiteB)
Topology says that Clients{10..19} prefer CS1@SiteA
If write_goal=1 then clients{10..19} will always talk to CS1@SiteA if available and only need to write there.
If write_goal=2 then clients{10..19} will write to both CS1 & CS2? (Perhaps the Custom Goal order would also need to be considered?)
Without any such feature, clients will need to wait for the remote high latency CS3 and/or CS4 to respond. I have been toying with blocking communications between clients at SiteA and chunkservers at SiteB to avoid such high latency writes from clients, while still allowing for chunkservers from all sites to still replicate among themselves in their normal lazy manor.

So, perhaps a new write_goal property which first considers topology(if applicable) and next considers the order in which custom goal targets are defined.

I may be misunderstanding what the chunk revision portion of chunks do. If they do not increment with each write such that non-written-replicas become "old", then perhaps this won't work.

Anyway, I hope something in this comment makes sense to someone, I find it slightly awkward to articulate it.

**Comment by Burning-Daylight** [comment]
@4Dolio I would like support your request: having an option like acknowledgement_goal would be absolutely great. Adding such an option would make LizardFS much more fit for a multi-site environment. At the moment geo-replication is half-functional since writes (except first) are essentially synchronous. In fact currently the "acknowledgement_goal" is defined by the number of replicas already present, which in my view is counterintuitive, since it is neither reliability-optimized, nor performance-optimized.
>  - If a chunk has goal=2 and two replicas exist, there is no possibility to successfully write and close a file without updating both replicas.
>  - If goal=2 and for some reason 4 replicas exist, all four of them need to be updated anyway.
>  - If goal=2 and only one replica exist, it is possible to successfully write this chunk by writing only this single copy (without a need to replicate it before writing

It would be nice to have at least an option to immediately remove outdated replicas when the chunk is changed, which would be equivalent to acknowledgement_goal=1.

**Comment by cloudweavers** [comment]
I strongly second @Burning-Daylight suggestion. An ACK_GOAL option would be great, and substantially improve the functionality for multisite configurations or clusters where nodes with great variation in IO speed are used.

**Comment by psarna** [comment]
Configuration option "REFUSE_ENDANGERED_WRITE" or alike should appear soon and it would cause master server to refuse creating/writing to chunks if it will make them endangered (i.e. losing any copy leads to data loss). It is not exactly a full "minimum goal setting", but it is a first step towards complete solution. If anyone has questions/remarks/suggestions, now is a good time to speak up.

**Comment by onlyjob** [comment]
"Endangered" means one replica (only) therefore proposed `REFUSE_ENDANGERED_WRITE` would block writes when only one chunkserver is available, regardless of goal (with exception for goal==1), right?

If I have file with goal 4 but only 3 chunkservers are available I still want such file to be writeable (as preventing write would case more harm than good).

Another way to express this would be making `GLOBAL_MINIMAL_GOAL` parameter that takes  (non boolean) value that works as follows:

~~~~
if {GLOBAL_MINIMAL_GOAL} >= {GOAL}
   and {GLOBAL_MINIMAL_GOAL} < {GOAL:satisfiable}
then
    REFUSE_WRITE()
fi
~~~~

With `GLOBAL_MINIMAL_GOAL=2` (sensible default?) it should work like (boolean) `REFUSE_ENDANGERED_WRITE` but with more flexibility.

This logic is easy to apply to replicated goals.

For EC goals `M==0` means "endangered" (where M is number of parity chunks) so we need to block writes if there are no available chunkservers to accommodate parity chunks.

**Comment by psarna** [comment]
Sounds good. Eventually full support for minimal goals and partial goals (writing only to goal X, which would then be replicated to goal Y) will be implemented as well, but **GLOBAL_MINIMAL_GOAL** should suffice for know and it is easy enough to be implemented without delay.

**Comment by Burning-Daylight** [comment]
"support for minimal goals and partial goals" sounds very promising!

**Comment by onlyjob** [comment]
This problem hit me (again) about a week ago. Here is the analysis:

Situation: a data folder with goal==3 (replicated); an application that writes data often; a fully replicated LizardFS cluster. One chunkserver is faster than two others and this chunkserver is being stopped (due to shut down of its host): a new chunk was accepted just before chunkserver was stopped before new chunk was replicated to other chunkservers. Result: missing chunk (goal==3) and frozen application despite two available/healthy chunkservers. Incident occurred during planned shutdown of a server for maintenance. This should have not be possible with enough chunkservers. (Of course starting chunkserver un-froze application and made missing chunk available).

Dear LizardFS team, please put on hold whatever you are working on until this problem is fixed. Thanks.

**Comment by blink69** [comment]
We will consider this scenario

**Comment by guestisp** [comment]
No updates on this ?

**Comment by MPaszkiewicz** [comment]
Here you can follow the current state of this feature:
http://cr.skytechnology.pl:8081/#/c/2665/

**Comment by guestisp** [comment]
Ok but any ETA for merge and release ?

**Comment by MPaszkiewicz** [comment]
It will most probably be merged within a week

**Comment by guestisp** [comment]
Awesome. This is a great improvement for data resiliency. After this, the only missing piece is a proper shadow promotion that doesn't lead to data corruption/loss

**Comment by onlyjob** [comment]
IMHO `REDUNDANCY_LEVEL` does not address this problem. See also #579.

**Comment by psarna** [comment]
Let's move the discussion to #579 entirely to avoid confusion. `REDUNDANCY_LEVEL` was created precisely to address this issue.

**Comment by pkali** [comment]
I agree. Closing then. Pls follow to #579
