### ISSUE TITLE
more detail on ha-cluster-managed

### ISSUE THREAD

**Issue by stela5** [lizardfs/lizardfs#266]
Can you provide more detail on **PERSONALITY = 'ha-cluster-managed'** ?
https://github.com/lizardfs/lizardfs/blob/master/doc/mfsmaster.cfg.5.txt#L37-L38

How do I achieve *remotly [sic] promoted to 'master'* ?

**Comment by psarna** [comment]
Details can be found in this commit message: https://github.com/lizardfs/lizardfs/commit/25aa102c9b0163eb61000bfb90b8917ee15b59c3 (and yes, we are aware that it contains some typos as well ;)).

Promoting ha-cluster-managed master is a responsibility of cluster manager,
you can explore https://github.com/lizardfs/lizardfs/tree/master/src/ha-cluster for some examples

**Comment by stela5** [comment]
Thanks for the info (and no worries on the typo, I just thought I'd mention it)!

Is this the correct workflow:

1. In mfsmaster.cfg use ```PESONALITY = ha-cluster-managed```
2. ```service lizardfs-master start``` will start the metadata server as **shadow**
3. A cluster management tool like Pacemaker/Consul/etc. uses a consensus algorithm like Raft or Paxos to perform leader election and then runs ```lizardfs-admin promote-shadow``` on the leader node
4. Use LizardFS normally
5. If the master node goes down, use the cluster management tool to detect it and elect a new leader and run ```lizardfs-admin promote-shadow``` on the new leader node.
6. If the original leader comes back up it will run as **shadow**

**Comment by psarna** [comment]
Not really.
First of all, `service lizardfs-master start` will fail, because a correct way of starting ha-cluster-managed master is `mfsmaster -o ha-cluster-personality=(master|shadow) ...` and it should probably be done inside some cluster manager script, not by hand.

Secondly, leader election is a complex task. Consider such sequence of events:
* Master with metadata version 5 fails
* Out-of-date shadow with metadata version 3 is elected and promoted
* Operations occur on filesystem, new master's metadata version jumps to 5
* Old master comes back to life with metadata version 5
* System is now in inconsistent state - 2 servers have same metadata version but different contents

so, you must take it into consideration when choosing a management tool.

**Comment by stela5** [comment]
Okay, sorry for so many questions but I'm just trying to understand the correct usage.  Do I need to create a mfsmaster.cfg file at all or should I just configure the master instances using the ```mfsmaster``` CLI?  

Once I run ```mfsmaster -o ha-cluster-personality=master``` on the desired master instance do I need to run ```service lizardfs-master start``` next or does the first mfsmaster command also start the master and I don't need to run that second command?

Also, what is the correct process for metadata failover?  I thought if a master fails a shadow could immediately replace it, but your description makes it sound like shadow instances don't reliably sync from the current master.

**Comment by psarna** [comment]
If you would like to use `mfsmaster -o ha-cluster-personality=master` command, you need to prepare mfsmaster.cfg file with `PERSONALITY = ha-cluster-managed` entry.
After launching master with the command above, it is not possible to control it via `service lizardfs-master XXX` interface, since it is now ha-cluster-managed (and, in particular, it is not possible to launch it again with `service lizardfs-master start`).

As for the metadata failover:
A shadow is, in most cases, perfectly capable of being promoted to master, but it cannot be guaranteed.  E.g. if some data packets are lost because of a faulty network, a shadow might not be up-to-date with current master. If it happens, promoting this particular shadow can be dangerous for data consistency.

This issue can be solved by keeping a global metadata version in some kind of distributed database,
as it is done in current implementation of lizardfs-cluster-manager. Then, automatic promotion can occur if and only if a shadow holds the most recent version of metadata.

**Comment by stela5** [comment]
Thanks!
