### ISSUE TITLE
mfsquota per directory?

### ISSUE THREAD

**Issue by weirdbricks** [lizardfs/lizardfs#304]
Hi there,

On MooseFS (2.x) I'm able to set quota per directory - example:

`mfssetquota -l 100M weirdbricks/100MB_MAX`

On LizardFS it looks like mfssetquota will only set the quota for the _entire_ mounted directory.

Is there anyway in LizardFS to set the quotas per directory under the same mount ? 

Another example:
`mfssetquota -l 100M mount_point/100MB_MAX/`
`mfssetquota -l 500M mount_point/500MB_MAX/`

Thanks!

**Comment by psarna** [comment]
Hi, 
setting quotas per directory is not supported. It's also not in our roadmap, since nobody ever requested it. If anyone is interested in this feature, there are 3 ways:
* wait (for undetermined amount of time)
* implement it (all kinds of pull requests are welcome)
* http://lizardfs.com/enterprise-support/ ;)

**Comment by psarna** [comment]
Oh, forgot to close this one. Per-directory quotas were implemented in 3.10: https://github.com/lizardfs/lizardfs/commit/b8adb3c5b70cae9e97db8b8756d7670be90fa88f
