### ISSUE TITLE
Kernel Panic running on Redhat 7 on compute engine.

### ISSUE THREAD

**Issue by tradergt** [lizardfs/lizardfs#310]
I was looking to see if lizardfs could be something we could replace our netapp with. However, I am getting these frequently on write. Its halted  one of the chunkservers already but most of the time they stay up.

Oct  7 20:47:59 sgclentcsrv03 kernel: mfschunkserver: page allocation failure: order:0, mode:0x20
Oct  7 20:47:59 sgclentcsrv03 kernel: CPU: 0 PID: 3228 Comm: mfschunkserver Not tainted 3.10.0-229.14.1.el7.x86_64 #1
Oct  7 20:47:59 sgclentcsrv03 kernel: Hardware name: Google Google, BIOS Google 01/01/2011
Oct  7 20:47:59 sgclentcsrv03 kernel: 0000000000000020 00000000bb499d49 ffff880026203b68 ffffffff81604516
Oct  7 20:47:59 sgclentcsrv03 kernel: ffff880026203bf8 ffffffff8115c5c0 0000000000000010 0000000000000000
Oct  7 20:47:59 sgclentcsrv03 kernel: ffff8800265d7800 00000000ffffffff 0000000000000001 00000000bb499d49
Oct  7 20:47:59 sgclentcsrv03 kernel: Call Trace:
Oct  7 20:47:59 sgclentcsrv03 kernel: <IRQ>  [<ffffffff81604516>] dump_stack+0x19/0x1b
Oct  7 20:47:59 sgclentcsrv03 kernel: [<ffffffff8115c5c0>] warn_alloc_failed+0x110/0x180
Oct  7 20:47:59 sgclentcsrv03 kernel: [<ffffffff81160d48>] __alloc_pages_nodemask+0x9a8/0xb90
Oct  7 20:47:59 sgclentcsrv03 kernel: [<ffffffff8155c569>] ? tcp_v4_rcv+0x6f9/0x7d0
Oct  7 20:47:59 sgclentcsrv03 kernel: [<ffffffff81536630>] ? ip_rcv_finish+0x350/0x350
Oct  7 20:47:59 sgclentcsrv03 kernel: [<ffffffff8119f3a9>] alloc_pages_current+0xa9/0x170
Oct  7 20:47:59 sgclentcsrv03 kernel: [<ffffffffa0149615>] try_fill_recv+0x4f5/0x570 [virtio_net]
Oct  7 20:47:59 sgclentcsrv03 kernel: [<ffffffff814fc258>] ? __netif_receive_skb+0x18/0x60
Oct  7 20:47:59 sgclentcsrv03 kernel: [<ffffffffa0149846>] virtnet_poll+0x1b6/0x730 [virtio_net]
Oct  7 20:47:59 sgclentcsrv03 kernel: [<ffffffff814fc6a2>] net_rx_action+0x152/0x240
Oct  7 20:47:59 sgclentcsrv03 kernel: [<ffffffff81077b3f>] __do_softirq+0xef/0x280
Oct  7 20:47:59 sgclentcsrv03 kernel: [<ffffffff81615c9c>] call_softirq+0x1c/0x30
Oct  7 20:47:59 sgclentcsrv03 kernel: [<ffffffff81015d95>] do_softirq+0x65/0xa0
Oct  7 20:47:59 sgclentcsrv03 kernel: [<ffffffff81077ed5>] irq_exit+0x115/0x120
Oct  7 20:47:59 sgclentcsrv03 kernel: [<ffffffff81616838>] do_IRQ+0x58/0xf0
Oct  7 20:47:59 sgclentcsrv03 kernel: [<ffffffff8160baed>] common_interrupt+0x6d/0x6d
Oct  7 20:47:59 sgclentcsrv03 kernel: <EOI>  [<ffffffff816144ab>] ? sysret_audit+0x17/0x21

**Comment by psarna** [comment]
Kernel panic is generally caused either by hardware error or a bug in the kernel. Since LizardFS is none of these, you should try to debug the issue in lower layers.

From what I can see in the stack trace, it looks like you failed to allocate a page, which suggests that you ran out of memory, which, in turn, suggests that swap didn't work for some reason (is it activated on your device?). 

Also, this is what I found on the first page of search results and it looks like it might help you:
https://access.redhat.com/solutions/90883.

Finally, I'm closing the issue, since it is not actually related to LizardFS - we do not provide kernel-space code (yet;) ), and that's where kernel panic comes from.
