### ISSUE TITLE
mfssetgoal timeout

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#329]
When I use `mfssetgoal -r` on large directory tree (~5_000_000 files) it throws

```
Can't read data from socket: timeout
```

when goal is actually changed. It temporary freezes master for ~10...15 seconds or so and interferes with all clients who get timeouts and connection resets.

Setting goal is not a high-priority task so I wouldn't mind if `mfssetgoal` take longer to finish but under no circumstances it should be able to temporary overload the master. 

This problem is somewhat similar to #267.

**Comment by psarna** [comment]
It is also related to #316, because of changed goal logic. This issue should disappear as soon as we deal with those bottlenecks, but we will schedule redesiging a setgoal mechanism as in #267 solution as well.

**Comment by kinosang** [comment]
Same problem here with 3.10.2

**Comment by kinosang** [comment]
Will this problem fix on 3.10.4?

**Comment by blink69** [comment]
@kinosang yes, we will patch that and release 3.10.4 in next few days

**Comment by psarna** [comment]
Fixed some time ago by adding `-l` option

$ lizardfs setgoal [-l] GOAL name [name ...]
 -n - show numbers in plain format
 -h - "human-readable" numbers using base 2 prefixes (IEC 60027)
 -H - "human-readable" numbers using base 10 prefixes (SI)
 -r - do it recursively
 **-l - wait until setgoal will finish (otherwise there is 30s timeout)**
 GOAL - set goal to given goal name
