### ISSUE TITLE
3.9.2: chunkserver crash: "Too many open files"

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#330]
Today, for the first time ever I've experienced crash of chunkserver:

~~~~
mfschunkserver[19456]: failed assertion 'pipe2(internalPipeFileDescriptors_, O_NONBLOCK) != -1', error: EMFILE (Too many open files)
~~~~

It appears to be a regression as I've never had anything like this on 2.6.0.

**Comment by onlyjob** [comment]
And apparently I have 1 missing chunk because of this... :(
Few hours prior to this incident I've changed goal of some files from __2__ to __xor2__.

**Comment by onlyjob** [comment]
I've searched logs for this particular error and found about a dozen incidents since upgrade to 3.9.2. My chunkservers have `Restart=on-abort` in .service file so they restart and work for some time until another crash... Maybe I'm hitting new limit for the number of open files?
New chunkservers log `open files limit: 10000` as per `/etc/security/limits.d/10-lizardfs.conf` while prior to v3.9.2 it was `open files limit: 65536`.
I'll double the limit and see if it help...

**Comment by onlyjob** [comment]
With doubled open files limit = 20000 chunkserver crashed within few hours. For now I bumped limit to 32768 (50% of what it was in v2.6.0) -- so far so good but a longer testing is necessary for confirmation and to build confidence.

Why chunkservers need to keep that many files opened at the same time?
Is there a possibility for a leak?

**Comment by psarna** [comment]
Files are being open more excessively if you have *splice* enabled. We will adjust the limits appropriately, since it looks like they are too low. 

Our tests cover open-files-leak detection, so it's not likely to be the case.

**Comment by onlyjob** [comment]
Interesting, thanks. For the record, crashing chunkserver have `USE_SPLICE` in its default value (i.e. `1`).

**Comment by onlyjob** [comment]
D'oh, it just crashed again despite limit=32768... :-(  Setting back to 65536 as in 2.6.0...

**Comment by onlyjob** [comment]
Actually it is not just about the limit. Crashing is wrong and there shall be some sort of fallback, logging errors like "not enough file descriptor available" or anything to prevent accidental abnormal termination of a chunkserver. I recommend adding test case specifically checking chunkserver behaviour to avoid crashing when open files limit is low.

**Comment by psarna** [comment]
You're obviously right - we are working on this, but it also implies checking if there are no more legacy mistakes like that, so it might take some time.

**Comment by psarna** [comment]
Could you check what kind of files are open in your chunkserver?
`lsof -p CHUNKSERVER_PID`
It will help us a lot, since it is not easy to reproduce your issue.
Helpful information would be: are most of the open files chunks, pipes, connections?

**Comment by psarna** [comment]
Also, it would probably help a lot to change line 76 in `hddspacemgr.cc` (chunkserver):
~~~
- #define DELAYEDSTEP 2
- #define OPENDELAY 5
+ #define DELAYEDSTEP 1
+ #define OPENDELAY 1
~~~

Generally, it is a legacy non-scalable definition that just happened to work until new version came across. Values above are used to set how often a check for files-to-be-closed occurs and it equals to **DELAYEDSTEP** * **OPENDELAY**.
  We will work on a smarter solution for this, but for now you could try to see if the simple workaround above helps your case.

**Comment by onlyjob** [comment]
> `lsof -p CHUNKSERVER_PID`

There are just about dozen pipes and over 25_500 chunks opened (last time I checked).
The chunkserver that crashes the most is configured with `HDD_TEST_FREQ=1`.

> `#define DELAYEDSTEP 1`
> `#define OPENDELAY 1`

I'm wondering it the above values would be better defaults.
What kind of implications one should expect if file handles are closed ASAP?

**Comment by DarkHaze** [comment]
> What kind of implications one should expect if file handles are closed ASAP? 
Most probably only slightly higher CPU usage. In case of some chunks increased delay (When information about chunk's file was removed from kernel cache).

**Comment by onlyjob** [comment]
Interesting, thanks. Actually removing closed chunks from kernel cache could have performance benefits.

**Comment by onlyjob** [comment]
Setting 

    #define DELAYEDSTEP 1
    #define OPENDELAY 2

on affected chunkserver dropped number of opened chunks from 25_500+ to ~500.
Thanks, @psarna.

**Comment by onlyjob** [comment]
It seems that chunkserver do not close file descriptors properly. Chunkserver with open files limit equal to 65536 and `DELAYEDSTEP 1`; `OPENDELAY 2` just crashed:

~~~~
Nov 27 16:05:31 debstor mfschunkserver[14923]: failed assertion 'pipe2(internalPipeFileDescriptors_, O_NONBLOCK) != -1', error: EMFILE (Too many open files)
Nov 27 16:05:32 debstor systemd[1]: lizardfs-chunkserver.service: main process exited, code=killed, status=6/ABRT
~~~~

It looks like changing goal from _xor2_ to _std2_ somehow triggered crash after some hours of replication while new chunks were created on this particular chunkserver.

**Comment by onlyjob** [comment]
Over the last 4 hours number of opened files grew to 40000 and continues to raise. (Checked with `lsof -p ${chunkserver_pid}`).

**Comment by psarna** [comment]
I'm working on a fix. Meanwhile, is your `HDD_TEST_FREQ` set low (1?). Temporarily, setting it to a higher value (say, 10) should release the open-files pressure on this chunkserver.

**Comment by onlyjob** [comment]
Actually changing `HDD_TEST_FREQ` do not help so I think problem is somewhere else.

**Comment by onlyjob** [comment]
Last 4 crashes happened with just about 2 hours interval between them despite `HDD_TEST_FREQ` set to a higher value...

**Comment by onlyjob** [comment]
Chunkserver appears to be running out of file descriptors faster when one or more chunkservers are down...

**Comment by onlyjob** [comment]
This issue is more serious than it looks: two chunkservers (with different labels) where data is replicating as per goal change (two replicas) crashed around the same time (to be precise, second chunkserver crashed while first was still scanning after abnormal restart). As result there are 10 new missing chunks and data loss... :(

**Comment by onlyjob** [comment]
Leak appears to be fixed -- thank you, Piotr. Great work.

However even though root cause for this particular leak was eliminated the bigger problem (segfault) is still there. When there are not enough file descriptors chunkserver might crash with loss of data. Abnormal termination should not be an option. Chunkserver is a mission-critical software that should not crash but instead perhaps refuse to do some operations, log errors or (in worst case) gracefully terminate. See [my other comment](https://github.com/lizardfs/lizardfs/issues/330#issuecomment-156183682).

Should we open another bug specifically for segfault or would you prefer to reopen this one?

**Comment by nickcoons** [comment]
Has this fix been applied to the deb packages available [here](http://packages.lizardfs.com/ubuntu/trusty/pool/main/l/lizardfs/)?  I'm using the 3.9.4 packages from there, and while manually setting the limits to 65536 helps, I'm still seeing the same chunkserver crashing issues anywhere from a few minutes to a few hours.  `lsof -p ${chunkserver_pid})` usually only shows a couple hundred files open.  This just began last night when I upgraded master and chunkservers from 2.6.0 to 3.9.4.

**Comment by 4Dolio** [comment]
I have been told not to use the vendor packages, which is what you linked to.  I see those vendor packages are dated 2015.12.16.  I think you may have better luck with the official Debian sources or building your own. I believe the Debian sources include more recent bug fixes.  Shrugs, I could very well be mistaken though.

**Comment by nickcoons** [comment]
Do you know the reason why it's not recommended to use the vendor packages?

I'm running Ubuntu Server 14.04, and they don't provide packages, which is why I've been using the vendor packages, and 2.6.0 worked great!  I typically try to use official packages rather than building from source, so if there's an issue, I'm using the same package that others are, and will likely find more commonalities when searching for support (and ruling out that the problem may be a bad build unique to my situation).  But if building from source is the best way to go, I may look into that option.

To clarify what I've done, I've added the /etc/security/limits.d/10-lizardfs.conf file with the following
`mfs soft nofile 65536`
`mfs hard nofile 65536`

But since I'm on Ubuntu 14.04, and using upstart, I believe that is ignored.  So I've created `/etc/init/lizardfs-chunkserver.conf` with the following:
`limit nofile 65536 65536`
`respawn`

The first line to set the limits, and the second line to restart the chunk server service if it crashes.  I added "respawn" later this morning, and it hasn't crashed since, so I don't know if this will work as I'm expecting.  But I'll be keeping an eye on it throughout the day.

**Comment by nickcoons** [comment]
Both of my chunk servers crashed again, and within two seconds of each other:

First server:
`Mar 20 11:08:47 aether mfschunkserver[32361]: failed assertion 'pipe2(internalPipeFileDescriptors_, O_NONBLOCK) != -1', error: EMFILE (Too many open files)`

Second server:
`Mar 20 11:08:46 ananke mfschunkserver[7892]: hdd_io_begin: file:/opt/lfs02/chunks9C/chunk_00000000019C658D_00000001.mfs - open error: EMFILE (Too many open files)`
`Mar 20 11:08:46 ananke mfschunkserver[7892]: hdd_io_begin: file:/opt/lfs02/chunksA7/chunk_0000000001A76F9A_00000001.mfs - open error: EMFILE (Too many open files)`
`Mar 20 11:08:46 ananke mfschunkserver[7892]: hdd_io_begin: file:/opt/lfs01/chunksA0/chunk_0000000000A0CE59_00000001.mfs - open error: EMFILE (Too many open files)`
`Mar 20 11:08:46 ananke mfschunkserver[7892]: hdd_io_begin: file:/opt/lfs01/chunks0A/chunk_00000000000ACD15_00000001.mfs - open error: EMFILE (Too many open files)`
`Mar 20 11:08:49 ananke mfschunkserver[7892]: hdd_io_begin: file:/opt/lfs01/chunksA0/chunk_0000000000A0CEC4_00000001.mfs - open error: EMFILE (Too many open files)`
`Mar 20 11:08:49 ananke mfschunkserver[7892]: failed assertion 'pipe2(internalPipeFileDescriptors_, O_NONBLOCK) != -1', error: EMFILE (Too many open files)`

It would be great to know if the vendor packages include the above-mentioned fix (I would assume they do since they were built ~two weeks after this issue was announced fixed).  If they don't, then I know that I need other packages.  If they do, then I know I need to look at a different issue to resolve this.

**Comment by onlyjob** [comment]
It is the best practice on Debian to use only packages from native repositories to benefit from integration, policy compliance, automated tests (QA, CI) etc. Vendors usually have little expertise in packaging and they rarely address/answer bugs in packaging etc. On this instance poor quality vendor LizardFS packaging is ages (more than a year) behind official Debian packages that maintained separately.
You can also read about this problem in https://www.zabbix.org/wiki/Appeal_against_public_upstream_packaging which is written about Zabbix vendor packaging but fully applies to this situation and quite correct in general.

To avoid duplication of effort Debian packaging is best to take care in Debian.

**Comment by nickcoons** [comment]
Thank you for the information about the vendor packages.  However, the vendor packages were built on 2015-12-16, so I don't see how they could be a year older than the Debian packages given that they are only three months old themselves.

The LizardFS authors may not have the packaging expertise, but it no doubt is better than mine, hence my reluctance to build from source. :-)

Am I better off using packages from Debian (rather than vendor packages) even through I'm running Ubuntu?

**Comment by onlyjob** [comment]
I can only say it again -- never ever use vendor packages especially if there are well maintained Debian packages from native repositories. And as Debian Developer and maintainer of [_official_ Debian packages of LizardFS](https://packages.qa.debian.org/l/lizardfs.html) I recommend to stay away from LizardFS vendor packages.
It doesn't matter when binary packages were generated from outdated and mediocre packaging... You can always re-build Debian packages yourself. If you are running Ubuntu you might benefit from switching to Debian. ;) Do not install foreign binary packages that was not built for your distribution. I don't know if LizardFS team provide binary packages for Ubuntu and personally I don't care for latter...

**Comment by nickcoons** [comment]
A switch from Ubuntu to Debian is on the roadmap for us, and thank you for the input.

**Comment by onlyjob** [comment]
> A switch from Ubuntu to Debian is on the roadmap for us, and thank you for the input.

I couldn't be happier to read that! :) Awesome. :) I hope you'll enjoy the experience.

**Comment by nickcoons** [comment]
I'm sure I will as I used to use it prior to 2005.  I only switched to Ubuntu because at the time Debian packages were often horribly outdated.  I understand that that's no longer the case, and that they're often times newer than Ubuntu LTS's packages.  So I'm looking forward to that!

Unfortunately, converting our LizardFS setup over to Debian is not going to be a quick change, and I still need to address the current issue on our setup.  `cat /proc/<pid>/limits` reveals that `Max open files` is indeed set to 65536 for the chunkserver process.  I've had no crashes for nearly three hours, so hopefully that resolves it.  If it does, I'll need to make permanent changes so that this survives a reboot.

I also have `lsof -p <pid> | wc` outputting to a file every second, so that if it does crash, I'll be able to see what the number of open files were just prior to the crash.

**Comment by onlyjob** [comment]
Ubuntu leeches most of their packages from Debian so Debian packages are usually ahead of Ubuntu. However you need to remember about suites like [_jessie-backports_](http://backports.debian.org/) providing more up to date packages for stable release.
One can use _testing_ suite if (s)he needs most recent packages.

One of the major problems with derivatives is that they take you one step away from source of knowledge, delay propagation of fixes, etc... In derivatives nobody cares for most packages and bug reports...

Official LizardFS Debian packages have workaround for max open files.

**Comment by psarna** [comment]
@nickcoons Also, this kind of error
`failed assertion 'pipe2(internalPipeFileDescriptors_, O_NONBLOCK) != -1', error: EMFILE (Too many open files)`
implies that your chunkservers work with splice enabled, which is not recommended anymore.
You can turn it off by adding
~~~
USE_SPLICE=1
~~~
to mfschunkserver.cfg.

**Comment by richard-scott** [comment]
Um, shouldn't that be:
```
USE_SPLICE=0
```
To disable it?

**Comment by psarna** [comment]
Obviously, thanks. It's always good to have perceptive community members :)

**Comment by nickcoons** [comment]
I've added `USE_SPLICE = 0` to `mfschunkserver.cfg`, but I haven't restarted the service yet for this to take effect.  So far, everything has been working normally now for over 21 hours, so I don't want to apply any other changes just yet as I want to keep my changes isolated so I know which changes have what real-world effect.  But I'm going to be doing some reboot tests after hours to make sure everything survives, and the change will be applied then.

Thanks!
