### ISSUE TITLE
3.9.2: client mis-handling old chunkservers

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#332]
On cluster upgraded to 3.9.2 I started old chunkserver v2.6.0 that was offline for a while.
Chunkserver joined successfully and (as expected) logged plenty of `got unknown message (type:1210)` messages.
When old chunkserver joined (at least) one of the 3.9.2 clients exhibited bunch of errors:

    mfsmount[8090]: write file error, inode: 36494179, index: 0 - Chunk write error (Disconnected) (try counter: 30)
    mfsmount[8090]: write file error, inode: 36494179, index: 0 - Read from chunkserver: connection closed by peer (server 192.168.0.89:9422) (try counter: 27)

resulting fatal error

    mfsmount[8090]: error writing file number 36494179: EIO (Input/output error)

which lead to abnormal termination of some applications.

Please improve client's error handling and fail-over in presence of old chunkservers.
IMHO this is a serious bug for anyone who upgrades LizardFS cluster.

**Comment by onlyjob** [comment]
Interesting to note that client did not try to fail over to other chunkservers and kept trying old one until failure.

**Comment by psarna** [comment]
Your problems are caused by a big mistake in UPGRADE notes, which stated that mounts and chunkservers can be updated in any order. From what I can see, 3.9.2 chunkservers are able to handle 2.6.0 mount requests perfectly well, but 3.9.2 mounts will not success in communicating with 2.6.0 chunkservers.
LizardFS's design does not offer any way for a 3.9.2 mount to realise, that it is talking to a legacy chunkserver (because its behaviour is indistinguishable from a faulty one - it breaks a connection after receiving a read/write request).

As for your second comment, we will take a closer look at that, expected behaviour should be to fail over to another chunkserver if such errors occur.

**Comment by onlyjob** [comment]
I'm not sure if I could isolate old chunkserver -- it was offline during upgrade and once powered on it joined automatically on boot which caused problems within minutes (almost immediately). In geographically distributed setup it might be difficult to ensure that all chunkservers are upgraded before any clients (think `apt-get upgrade`) therefore proper failover is very very important.

**Comment by psarna** [comment]
It worked like that since the beginning of LizardFS and changing this logic will be a serious change, but it is actually involved in a bigger improvement, which is already on our roadmap.

**Comment by psarna** [comment]
A word of comment - after applying 5bf1dd1 an old chunkserver will not cause client errors, as long as  chunks requested for writing are also available on 3.9.2 chunkservers.

**Comment by onlyjob** [comment]
Excellent. Thank you very much. 
Please remember to check client's failover to another chunkserver too.
