### ISSUE TITLE
3.9.2: client read errors on SQLite WAL file

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#334]
Since upgrade to 3.9.2: my browser (_Icedove_ aka _Firefox_) freezes for minutes several time a day. _mfsmount_ logs the following:

    read file error, inode: 4171408, index: 0, chunk: 166529610, version: 182 - no valid copies (try counter: 19)

_inode: 4171408_ is a file `~/.mozilla/firefox/oqtqcgn2.default/places.sqlite-wal`, size about 300 kB and only one chunk (_mfsfileinfo_):

~~~~
          chunk 0: 0000000009ED0A4A_000000B8 / (id:166529610 ver:184)
                copy 1: 192.168.0.2:9422:A
                copy 2: 192.168.0.250:9422:B
~~~~

Goal of this file is __3__ however LizardFS can't make a third copy for a week due to ongoing goal change (_2_ to _xor2_) of other files.

I understand that file is frequently re-written so it is strange to get read errors on the local machine which modifies the file. I don't recall having such problem in 2.6.0.

**Comment by psarna** [comment]
Well, to start with, I discovered undeniable evidence of pure idiotism in client code and fixed it:
http://cr.skytechnology.pl:8081/#/c/2259 - it might just help.

And now to the point. Is it possible that chunkservers 192.168.0.2 and 192.168.0.250 are sometimes not available for a while (or, perhaps, contain a different version of the chunk)? Chunk version is changed when chunk is known to be on a chunkserver that is down, and it is changed on the rest of servers.

It is *theoretically* possible that because of erroneous 60 second waiting period between retries, this chunk was accessed for writing, its version changed, and then a chunkserver with the current version became down for a while. This is a *really* far-fetched scenario, though.

**Comment by onlyjob** [comment]
Thanks, Piotr. So far 43b62fa7 was a big relief.

As far as I can tell chunkservers are available, serving other requests etc. I've specifically checked their logs and found no errors. Master did not complain about anything either.
The whole thing seemingly caused by a simple short/temporary timeout on client side during communication with chunkserver(s).

Once in a while I'm getting the following from client:

    write file error, inode: 2532059, index: 4 - Chunkserver timed out (server 192.168.0.250:9422) (try counter: 1)

but now it recovers really fast.
