### ISSUE TITLE
lizardfs-admin manage-locks requires password

### ISSUE THREAD

**Issue by richard-scott** [lizardfs/lizardfs#345]
I've noticed that the use of 'lizardfs-admin manage-locks' requires the mfsmaster to be configured to use a password:
```
# lizardfs-admin manage-locks 10.0.0.2 9421 list all
Admin password:
Active flocks:
Pending flocks:
Active POSIX locks:
Lock:
        inode: 3
        owner: 18444105188766230516
        sessionid: 1
        type:  exclusive
Pending POSIX locks:
#
```
I can't see any destructive options that you can use, so is it right that this one enforces a password?
Other lizardfs-admin commands work without enforcing a password such as ready-chunkservers-count.

**Comment by psarna** [comment]
It is caused by another manage-locks functionality, namely **unlock**. Separating those functionalities shouldn't be too hard, but, on the other hand, manage-locks **list** does expose some (private) metadata of the whole system, so maybe it's not that stupid to ask for an administration password first.

**Comment by onlyjob** [comment]
`lizardfs-admin manage-locks mfsmaster 9421 unlock posix --inode=$N` is an example of destructive command that requires a password. Although it only removes lock there is a potential security risk of exposing such commands to unauthorised users.

**Comment by richard-scott** [comment]
ok, thanks for clearing that up.
