### ISSUE TITLE
ping_pong lock file support

### ISSUE THREAD

**Issue by richard-scott** [lizardfs/lizardfs#346]
Hi,

Global file locking does not seem to be compatible with the CTDB daemon from Samba.
To test it, you can use the [ping_pong](https://wiki.samba.org/index.php/Ping_pong) comand:

```
# ping_pong /mnt/volume/pp.lock 3
```

Obviously my LizardFS volume is mounted at /mnt/volume on each node.

Thanks,

Richard.

**Comment by psarna** [comment]
How many nodes do you have?

Quoting samba wiki on ping_pong test:
Login to several nodes of your cluster. Start by running ping_pong on just one of the nodes like this:
ping_pong test.dat N
**where N is at least 1 more than the number of nodes you will be testing on**.


I'm asking because we do have a test in our suite that runs ping_pong binary from samba.

**Comment by richard-scott** [comment]
I have only two nodes, and when I run this:
```
# ping_pong /mnt/volume/pp 3
```
the lock count goes up on both nodes... as far as I'm aware, it should only go up on the node that has the lock allocated?

**Comment by psarna** [comment]
Nope, that would mean the system is buggy. Ref: https://wiki.samba.org/index.php/Ping_pong#How_it_works

I'm closing the issue, I'll reopen if some other problems with ping pong show up.
