### ISSUE TITLE
File lock still active after server power reset

### ISSUE THREAD

**Issue by richard-scott** [lizardfs/lizardfs#351]
### My Setup
I have a single VM that runs everything: master, chunkserver and mounted volume.

### Problem
After mounting the volume, starting a deamon that locks a file with an exclusive posix lock, and then hard rebooting the system (with the reset VM button) the file lock is still in place after the reboot.

This is odd as I would expect there to be no locks active after a reboot as no process can own the existing lock.

Also, I can't see a way to find out what lock is for what file in the volume. All I can find is this:

```
SSHPASS=password sshpass -e lizardfs-admin manage-locks 10.0.0.2 9421 list all --active
Active flocks:
Active POSIX locks:
Lock:
        inode: 3
        owner: 13459613027694958360
        sessionid: 2
        type:  exclusive
```

Is there a way to identify a lock by volume path file name?

**Comment by psarna** [comment]
Orphan locks are cleared when its session times out, which can be set with SESSION_SUSTAIN_TIME configuration option master (default: 24h, which is longish).

You have the inode number, so you can:
a) search, e.g. by Linux's find command
`find -inum n .`
b) ignore the path and force-unlock the lock with admin tool,
`lizardfs-admin manage-locks 192.168.0.1 9421 unlock posix --inode X`

**Comment by onlyjob** [comment]
@richard-scott, I believe this is correct behaviour and to my knowledge all network file systems supporting locks are behaving alike.
When locks are not explicitly released by client, server can only expire locks after some time. There is no way of telling if machine suddenly lost power or if it is just a temporary loss of connectivity. Also you could have suspended machine in which case one might expect locks to survive at least for some time instead of being dropped immediately.
IMHO this is not a bug but a thing to keep in mind when working with network file system.
Also you can disable locks if you mount LizardFS with `enablefilelocks=0` option.
