### ISSUE TITLE
3.9.4: FTBFS@kfreebsd: "src/common/portable_endian.h:151:2: error: #error platform not supported"

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#354]
3.9.4 FTBFS on kFreeBSD:

    src/common/portable_endian.h:151:2: error: #error platform not supported

See build logs for [kfreebsd-amd64](https://buildd.debian.org/status/fetch.php?pkg=lizardfs&arch=kfreebsd-amd64&ver=3.9.4%2Bdfsg-1&stamp=1449683343) and [kfreebsd-i386](https://buildd.debian.org/status/fetch.php?pkg=lizardfs&arch=kfreebsd-i386&ver=3.9.4%2Bdfsg-1&stamp=1449684072).

This is a regression as 2.6.0 builds fine.

**Comment by onlyjob** [comment]
kFreeBSD sometimes used in storage systems due to native ZFS support. IMHO it is fairly important to maintain compatibility with (k)FreeBSD.

**Comment by Zorlin** [comment]
My previous employer had many FreeBSD chunkservers, as performance was
slightly better on FreeBSD at the time - and also because of the stable
support for ZFS. We wanted to move everything to individual XFS disks
running on Debian 7 (I imagine that would be Debian 8 now) but that didn't
happen before I moved away.

**Comment by Zorlin** [comment]
Oh, never mind. I thought FreeBSD and kFreeBSD were the same thing :)

**Comment by onlyjob** [comment]
Interesting... From compilation prospective kFreeBSD and FreeBSD are pretty close...
kFreeBSD allows to use nearly full power of GNU+Debian with FreeBSD kernel instead of Linux. :)

**Comment by onlyjob** [comment]
Thank you!
