### ISSUE TITLE
shadow could not sync after restart of master

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#397]
On 3.9.4 I've restarted _master_ and noticed muiltiple errors indicating that _shadow_ is unable to sync.

On _master_ (multiple errors):

~~~~
LIZ_MLTOMA_CHANGELOG_APPLY_ERROR, status: Metadata version mismatch - refusing to store metadata because only 823 seconds elapsed since the previous request and METADATA_SAVE_REQUEST_MIN_PERIOD=1800
...
LIZ_MLTOMA_CHANGELOG_APPLY_ERROR, status: Metadata version mismatch - refusing to store metadata because only 824 seconds elapsed since the previous request and METADATA_SAVE_REQUEST_MIN_PERIOD=1800
...
LIZ_MLTOMA_CHANGELOG_APPLY_ERROR, status: Metadata version mismatch - refusing to store metadata because only 853 seconds elapsed since the previous request and METADATA_SAVE_REQUEST_MIN_PERIOD=1800
~~~~

On _shadow_ (multiple errors):

~~~~
some changes lost: [8134293314-8134377600], download metadata again
some changes lost: [8134293314-8134377601], download metadata again
some changes lost: [8134293314-8134377659], download metadata again
Waiting for master to produce up-to-date metadata image
~~~~

From CGI interface I observed that _shadow_ metadata version fell behind _master_ and was not catching up. Shadow and master communication remained in seemingly endless loop for 20+ minutes and restart of _shadow_ did not help to recover from the problem.

What happened is that I've applied d21d297e on _master_ and restarted it so _shadow_ was one patch behind. Situation normalised after restart of patched _shadow_.

I have two thoughts regarding this incident:

 * Perhaps it could be safer if shadow were able to synchronise with newer master. Then in case of a problem on master (like crash shortly after upgrade) I could try to promote still unpatched shadow to recover. Though I imagine it could be actually good if shadow could not synchronise so in case of a problem on master I could revert to last safe metadata version. I did not make up my mind about it yet.

 * Clearly better error reporting would be useful. It is nice that _shadow_ tried to recover relentlessly but it produced a lot of noise that was not particularly helpful to determine the problem.

Also I don't quite understand why shadow could not synchronise so there might be a bigger problem.

Any thoughts? Please feel free to close this bug if there is nothing to improve here.

**Comment by psarna** [comment]
Here's why it happens:
* master updated with d21d297 performs unlink operation, which now sets **atime** instead of **ctime** of chosen inode;
* master computes the checksum of given inode and broadcasts to shadows that unlink was performed;
* shadow, not yet updated, receives unlink request for inode 1234 and performs unlinking,
setting **ctime** of inode 1234;
* shadow computes the checksum of given inode, which differs from the one sent by master (because master updated node's atime, while shadow updated its ctime);
* checksum mismatch.

From shadow's perspective, master indeed failed to produce up-to-date metadata image, because it just looks like it computed inode's checksum incorrectly. I agree that shadows are particularly noisy when they fail to get along with master, but, on the other hand, it _should_ be an alarming situation.
Perhaps we should make shadows less verbose when they continuously fail to get metadata from master server.

**Comment by psarna** [comment]
Also, there is a way to avoid such situations without changing the intentions of d21d297 too much and I'll prepare it in a minute.

**Comment by onlyjob** [comment]
Makes sense. Thanks for your explanation, Piotr.
