### ISSUE TITLE
Small (2 Server) Cluster Home Server Support

### ISSUE THREAD

**Issue by AnalogJ** [lizardfs/lizardfs#400]
I know this probably isn't the best way to get answers, but no one was answering on the IRC channel. I also took a look at the wiki and [whitepaper](https://lizardfs.com/wp-content/uploads/2015/09/LizardFS_WhitePaper_Eng_v3.pdf).

What I'm looking for is a bit complicated, so bear with me. 
I have 2 linux servers, one at my home on the west coast (California) and one located at my parents home in Canada. 

My server in California has all my new ripped movies, photos and audio albums, while my parent's server has a mix of older ripped movies and new Bluerays that by brother has ripped. 

Both servers have approx 10TB of storage.

Here's what I'm looking for:
- a storage filesystem that will allow me to remote mount/merge my distributed drives such that I (or my family) can access all our movies from a single Plex server. 
- the FS doesn't need to be redundant (like RAID) for our movies however we would like the option of distributing certain media (like our photos) across both locations
	- basically I want to be able to add media to one location and not have it automatically mirror to the other location unless I want it to
	- at the same time, the data in the drive should be "virtual" and stream over the network when requested at a remote location (for Plex)
- it should be easy to add physical drives into a JBOD style local virtual disk (so I can continuously increase my local storage)
- it should be easy to recover data if the virtual disk fails
	- I should be able to remove and plug in the drive to another computer and copy off all the media stored on the drive. 

I've been using Greyhole with great results on my California server, and it basically does everything I listed except handle physically distributed disks

I've looked at a bunch of alternatives but LizardFS seems like it could work for me, but the [configuration page](https://github.com/lizardfs/lizardfs/wiki/Quick-Start-Guide#configurations) specifies that I should **"NEVER EVER put a metalogger on the same machine as the master server, it's a terrible idea"**

I only have 2 servers, mostly large files, mostly read IO and the occasional write IO. Is it still a huge issue to have the metalogger, master and chunk server all run on the same hardware?

**Comment by richard-scott** [comment]
Hi,

I would say that due to the need for a master daemon to be running on a server that LizardFS is not the right thing for you. Have you looked at [GlusterFS](https://www.gluster.org/), that does rsync replicaton of volume data, but I'm not sure about two way replication.

Without duplicating ALL the data in both locations, I can't see how this could work.

We have a similar setup at work where we have an Editorial server, that has an "incoming" folder for new files, and a "master" folder that is rsynced out to other nodes. Users upload new files into "incoming" some crontab scripts move these files into "master" and then rsync distributes it all aroundthe world. When data is then accessed, users do so via the read-only "master" folder.

It's a bit complicated, but works for us :-)

Rich

**Comment by psarna** [comment]
Oh, as for the **"NEVER EVER put a metalogger on the same machine as the master server, it's a terrible idea"**, it's not like anything would explode. You just need to understand that metaloggers are used as a backup copy of master's metadata, so putting it on the same server as the master is like creating a backup copy of your files on the same disk you already store them.
If you have 2 servers, there is literally nothing wrong with this configuration:
~~~
server A: 1 master, 1 chunkserver
server B: 1 shadow, 1 chunkserver
~~~
Metaloggers are completely optional. If you decide to put one on a spare machine (e.g. your old PC), it will just make your metadata even more safe.

As for replication policies (create one copy on specified server, create copy on any server, create 2 copies), that's exactly what labels and goals are for. Adding another physical disk to your cluster is easy as well.

Summary: if your only concern was the **"NEVER EVER put a metalogger on the same machine as the master server, it's a terrible idea"** sentence then we had a misunderstanding, metaloggers are completely optional and your metadata is safe anyway since you have a shadow server.
