### ISSUE TITLE
lizardfs-master.init script

### ISSUE THREAD

**Issue by druschka** [lizardfs/lizardfs#414]
after the case part you should change LIZARDFSMASTER_CONFIG_FILE to CONFIG_FILE or the right config file will never be added with "-c conffile"

**Comment by MPaszkiewicz** [comment]
Hi @druschka,
The way it currently works is that LIZARDFSMASTER_CONFIG_FILE will be used as a config file only if this variable is specified. Otherwise, mfsmaster will run without parameters, meaning that it will use the default config file.
I'm not sure what kind of issue is that you experience, could you explain it a bit more?
