### ISSUE TITLE
Master and chunk server connections - External chunk

### ISSUE THREAD

**Issue by htbase** [lizardfs/lizardfs#423]
Hi there

We have a few local servers where we use LizardFS

The local chunk servers all connect well to the master. We have recently got a remote server that we wanted to use the disks and connect it to the lizard master server.

I was able to install lizard chunckserver in that remote server and do an mfsmount so we see the files. It all seemed to work fine but when I look at the logs, I see this:

mfsmount[27316]: read file error, inode: 2, index: 0, chunk: 1, version: 5 - Can't connect to 192.168.0.235:9422 (try counter: 20)

the 192 IP is the internal network IP. We need to get mfsmount to point to our public IP to be able to point to the external IP

We have tried using the -H option and it mounts fine but when we do reading and/or writing, it still tries to use the internal IP

Would appreciatte any help

Thanks

**Comment by MPaszkiewicz** [comment]
Hi,
The only way to make it work right now is to set both local and remote chunkservers to use public IP of master.
In order to do that you have to configure all chunkservers to connect to master using his public IP and in master config file set MATOCS_LISTEN_HOST=<masterPublicIP>
In case you need a dedicated/custom solution, you could contact support@lizardfs.com

**Comment by htbase** [comment]
If I do so, I see the following error:

[FAIL] master <-> chunkservers module: can't listen on 99.224.213.159:9420: EADDRNOTAVAIL (Cannot assign requested address)
[FAIL] init: communication with chunkserver failed

I have a Master and Chunk installed in the same server, not sure if that is responsible for causing this issue

**Comment by htbase** [comment]
If I keep binding the local master and chunk server to the local IP, it works fine. The remote server can then work well with the remote IP

Problem then happens when I try mfsmount from remove server, then we are back to the same scenario

**Comment by psarna** [comment]
Master and chunkserver are perfectly capable of running on the same machine. You can check if something already listens on this specific address and port with `netstat -lp` or any other network diagnostics tool. "Cannot assign requested address" can also be caused by the fact that address xx.xxx.xxx.xxx is for some reason not valid for this machine - a typo perhaps?

If you bind local chunkservers to local master host, then master keeps local chunkserver addresses in memory. Then, if remote mount asks for a chunkserver, it receives a local address (perfectly valid from master's point of view) and cannot connect to it.

On second thought, would you consider some kind of VPN? It should solve your problem as 'remote' mounts would appear to be 'local'.

**Comment by htbase** [comment]
There is no process running on that port, what happens is that in order to do that solution, our external IP (internet IP) would need to be assigned to the Master host, which is not an option

I guess we would have to do VPN

Thanks
