### ISSUE TITLE
Unstable - stables version ?? lizardfs-master 3.10.1.1453 Debian Wheezy

### ISSUE THREAD

**Issue by andypl78** [lizardfs/lizardfs#437]
I have many problems with new lizardfs-master on Debian Wheezy from i think "stable" repo http://packages.lizardfs.com/debian/wheezy

Now lfs master die and i have this in log files

mfsmaster[826]: segfault at 0 ip 00000000004f85e5 sp 00007ffdd8a12980 error 4 in mfsmaster[400000+157000]

**Comment by psarna** [comment]
Hi,

http://packages.lizardfs.com/debian/wheezy contains stable 3.10.0, 
trailing '1' in version you quote (3.10.1) suggests it is unstable. What 
is your output of `mfsmaster -v`? If it's 3.10.1, then you are not 
running a binary from stable release.

**Comment by andypl78** [comment]
I installed version 3.10.1 of your repo.
I checked today, but you have now version 3.10.0
Perhaps for a moment you had a version 3.10.1 on your repo and then updated it from you?

**Comment by andypl78** [comment]
Is it possible to do a downgrade from 3.10.1 to 3.10?
Now I am downloading manually 3.10 for clients and chunk  servers and installed manually, but I do somehow downgrade master.

**Comment by psarna** [comment]
If 3.10.1 was downloaded from our official website then it was definitely
an error and should not happen. Our stable versions can be recognized by
having even minor number, e.g. next stable release will most likely be
3.10.2. If 3.10.1 was somehow available from our repository then all I can
do is apologize and suggest installing 3.10.0. Fault you mentioned was most
likely due to https://github.com/lizardfs/lizardfs/issues/422 , which is in
unstable tree and was fixed in
https://github.com/lizardfs/lizardfs/commit/4d361b9c4ef63624c4e604e128f3ffd227d4adea
.

**Comment by onlyjob** [comment]
Wheezy is an _oldstable_ release of Debian. Wheezy is already obsolete with only minimum support provided as per LTS. One should upgrade to _Jessie_ where official LizardFS packages are available from "jessie-backports" suite. Also I recommend to avoid vendor packages whenever possible and use only official Debian packages from native Debian repositories.

**Comment by Anoneko** [comment]
Hi,

I have same problem with LizardFS 3.10.2 on Ubuntu 14.04.1.
The cgi panel showed lfsmaster died at 19:00 but I did not get any log until 19:48

Sep 29 19:48:14 bk kernel: [427434.551276] show_signal_msg: 48 callbacks suppressed
Sep 29 19:48:14 bk kernel: [427434.551283] mfsmaster[1220]: segfault at 0 ip 00000000004d4137 sp 00007ffd2a5a1010 error 4 in mfsmaster[400000+134000]
