### ISSUE TITLE
set goal by last modified date?

### ISSUE THREAD

**Issue by biocyberman** [lizardfs/lizardfs#441]
I am trying out LizardFS and got it working. It is actually very easy to setup. However, I still have many questions unanswered. One of the most burning one: Is there any convenient way to set goal by file/directory last modified date and access frequency? For example: If directory /mnt/lizardfs/olddata has not been modified  or not read more than 5 times for last 3 months, I want to set goal for it so it get moved to a slower storage device.  I can write a script to find out the information about last modified date, and set goal. But I dont know about access frequency, maybe there is something we can use native lizardfs functionality like it is used in the lizardfs-cgiserv module? 

I am running lizardfs 3.10 on Ubuntu Trusty and Xenial.

**Comment by MPaszkiewicz** [comment]
Hi,
Currently this kind of functionality is not implemented, although it might be added in the future.
One way to make it work right now would be to write a script that could measure and detect files which are accessed less frequently and set goals accordingly (a very simple database should suffice).

**Comment by biocyberman** [comment]
+1 This feature in the future releases.

**Comment by onlyjob** [comment]
I strongly disagree with this feature request. Storage system should not change goals automatically due to potential of congestion, endangering data, compromising reliability, etc. Goals typically assigned according to data importance, not access frequency. You can optimise access latency by using SSD caching techniques such as _dm-writeboost_, _EnhanceIO_, _external ext4 journal_, etc. What should be implemented instead is native chunkserver caching or chunkserver _cache tier_ #270 or master level cache tier #271. Also improving flexibility of topology settings #269 to have better control over data location could be helpful.
Besides having global per-file hits count will negatively affect memory usage on master... :(

**Comment by 4Dolio** [comment]
I am very interested in the referenced #269 and another feature request i can not find while on vacation which would allow for a chunk server to be given multiple labels.  Beyond that i have pseudo coded scripts to leverage find and perhaps snapshots to provide a sort of tiered goal solution, which I agree should remain outside the scope of a native feature for now.
