### ISSUE TITLE
Release 3.10.1

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#449]
3.10.0 appears to be released without fixes for #422 which IMHO makes releasing 3.10.1 an immediate priority.
As far as I'm aware current state of "master" is ready to be released as 3.10.1.
Let's release it ASAP as per #440.

What's left to do to release 3.10.1?

**Comment by psarna** [comment]
1. Some more commits related to https://github.com/lizardfs/lizardfs/commit/23e3af5ac794c0cb790abefa712a6ec40eabd1d9. It is a replacement for client tools, which would now be bundled in one `lizardfs` binary. Details are available in commit message. All backward compatible of course.
2. Implementing a task manager for lengthy operations: snapshot, setgoal, settrashtime, etc. It would make all these operations asynchronous, so master will not hang for several seconds on huge directory trees anymore.
3. #227 is a candidate as well since it looks simple enough

**Comment by onlyjob** [comment]
Great: it looks like 2. is going to fix #329...

**Comment by psarna** [comment]
#329 and any future issues with lengthy commands. They are redesigned at their core so it will take some time to test them all properly, but in the end master would become even more responsive, which is one of the priorities right now.

**Comment by Asher256** [comment]
Question: what is the safest way to update LizardFS master / shadow / chunkserver / metalogger? Do I need to follow a certain order?

Thanks.

**Comment by psarna** [comment]
https://github.com/lizardfs/lizardfs/blob/master/UPGRADE

**Comment by Asher256** [comment]
Thank you Psarna!

**Comment by biocyberman** [comment]
@Asher256 Good that you asked. I learn a new thing as well.

**Comment by onlyjob** [comment]
Fixed by 3.10.2. Thanks.
