### ISSUE TITLE
LizardFS Debian packages + packages.lizardfs.com are different

### ISSUE THREAD

**Issue by Asher256** [lizardfs/lizardfs#456]
Hi,

I've noticed the Debian packages https://packages.debian.org/source/jessie-backports/lizardfs and the packages from packages.lizardfs.com are different:
- /etc/mfs instead of /etc/lizardfs 
- mfs user and group instead of lizardfs
- /var/lib/mfs for the metadata instead of /var/lib/lizardfs

It is confusing for people who want to automate the installation of LizardFS because the default values are not the same depending on the package source. It would be better if the default directories were unified.

I suggest you to unify the default user / directory in packages.lizardfs.com with Debian. The user/group lizardfs and the directory /etc/lizardfs is a good choice because LizardFS is not MooseFS and shouldn't share the same directories as MooseFS. It could also be the opposite (Debian unified with your packages, with a backward compatibility).

I've noticed this because I'm developing a Puppet module to automate the configuration of LizardFS https://github.com/Asher256/puppet-lizardfs and I added a new parameter today (manage_repos=true) to give to the users the possibility to use the repository packages.lizardfs.com instead of the Debian repositories. I'll try to find a solution for my automated module, but it is a little bit confusing. I will maybe force some parameters on all operating systems (like /etc/lizardfs for example) to avoid this kind of issues.

Thank you.

Asher256

**Comment by Zorlin** [comment]
If you are running Debian, you should use the official packages (on debian
repos), not the LizardFS "vendor" packages. For various reasons.

**Comment by Asher256** [comment]
@Zorlin: can you tell me more about the reasons why it is better to use the Debian repositories instead of the "vendor" packages? Thank you.

**Comment by onlyjob** [comment]
As I understand vendor packages exist mostly for continuous integration purposes... Unlike official packages from Debian repositories, vendor packages are poorly maintained and their quality is not up to Debian standards... I don't know how good vendor packages are for other GNU/Linux distributions but on Debian it took months of work to prepare official LizardFS packaging...

**Comment by Zorlin** [comment]
@onlyjob handles the official Debian packages (I think?). Where appropriate
he cherry-picks fixes and overall does a great job of the packaging.
Whereas the vendor packages handle the first 80% of packaging great but
kinda fall down on the last 20%. The official Debian packages follow
guidelines and packaging rules to the letter, the vendor ones ignore them.

Functionally they should both be the same, but the Debian packages are
possibly slightly more stable due to getting fixes faster.

**Comment by onlyjob** [comment]
> @onlyjob handles the official Debian packages

He certainly does: https://packages.qa.debian.org/l/lizardfs.html    ;)

> why it is better to use the Debian repositories instead of the "vendor" packages?

Mostly due to separation of responsibilities. Upstream job is to look after code. Downstream better understands integration with distribution, policies, best practice, etc.

If you use Debian, chances are that it is in parts because of rich coherent free software repositories that Debian offers. Unlike Windows that comes without software or RHEL which offers poor minimalistic software repository, Debian provides more than 50_000 packages, peer reviewed, built for many architectures in clean environments, with security support, transparency, continuous integration, single bug tracker, etc. -- all for better quality, security, convenience and confidence.

Installing software from digitally signed packages from native repository provide significant advantages and added value as well as better user experience. 

Ultimately the best way to ship software on Debian is to maintain official packages. Naturally you would expect vendors to work with (or become) maintainers of Debian package, otherwise why bother with packaging software for Debian unless it is intended to become part of Debian distribution?
Yet is not always the case.
Here is relevant quote of two Debian Developers discussing where is the
best to maintain Debian package -- upstream and/or in Debian:

>> If the packaging folder stays until the package reaches Debian, that's
>> fine. However, if it stays after that, it's bad to have it upstream,
>> even if it's not conflicting with our workflow. Why? Well, simply
>> because instead of a single place where to contribute to the packaging,
>> you now have 2: one upstream, and one in Debian. Once one or the other
>> gets updated, who's going to do the work of propagating the change in
>> the other place where the packaging information is stored? What's the
>> point of having double the work to update the debian folder in both
>> Debian and upstream? Just get that done in Debian, and that's it...
>
> I see no motivation on the upstream site to follow different Debian
>revisions, closing bugs in the debian/changelog etc.  Thus a single
>place of maintenance is best maintained in a repository controlled by
>Debian...

  * https://lists.debian.org/20150610062931.GB15148@an3as.eu

With all due respect to upstream developers, with their own disconnected "vendor" packages they always lack incentive to follow/answer Debian bug reports and meet Debian standards and policy requirements. I've never seen this working in any project. Here is a brilliant example of notoriously poor quality vendor packages: https://support.zabbix.com/browse/ZBX-7996

The following link explains problems with vendor packages -- a fascinating summary:

  * https://www.zabbix.org/wiki/Appeal_against_public_upstream_packaging

Please note that the problem is not specific to Zabbix. This is a typical case with unofficial packages.

As for LizardFS I believe there is a room for improvements to release process. Perhaps LizardFS team could reduce their maintenance burden by working on official Debian packages instead of maintaining their own (significantly diverged) packages. I reckon we need to figure out how exactly this could be done and coordinate our efforts better...

**Comment by biocyberman** [comment]
Reading from this issue, I can see the advantages of stability of the official packages. However, I see one advantage of vendor package as well: 
They can always release the latest versions and bug fixes quickly. I haven't used Debian for several years now so I don't remember, but on Ubuntu the release cycles have thresholds. For example, just saying, for Ubuntu 14.04 the version can only be 3.9.xx. And people have to upgrade to newer Ubuntu to get 3.10.xx.  

To avoid this constraint, people use PPAs. Maybe LizardFS can also do that for Ubuntu?

**Comment by onlyjob** [comment]
On Debian we provide some newer software in "jessie-backports" suite. Those upload typically follow packages in "testing".

> To avoid this constraint, people use PPAs.

Where people can do anything they want because they do not have to comply with policy? I understand PPAs are notorious for poor quality packages...

I think single centralised official repository where maintainers cooperate is better.

> Maybe LizardFS can also do that for Ubuntu?

Why? Ubuntu leaches almost everything from Debian, including LizardFS. We can't stop anyone from maintaining LizardFS packages in PPA (and some might find it useful) but IMHO it would only add to confusion and fragmentation...

**Comment by biocyberman** [comment]
> I think single centralised official repository where maintainers cooperate is better.
I agree. I only want to add that centralised official repo should  take care of Ubuntu users. PPA is one way to pass in the latest version without restrictions of Ubuntu release cycle.  

> Why?
Because of the reason I mentioned just above about the release cycle restriction.

> Ubuntu leaches almost everything from Debian, including LizardFS. We can't stop anyone from maintaining LizardFS packages in PPA (and some might find it useful) but IMHO it would only add to confusion and fragmentation...
I see the "leaching" is a good thing, making Ubuntu a "faithful" (in the sense of package collection) descendant of Debian. So I don't have to worry I miss something for the vast collection of Debian. Therefore a PPA, which convert all package of the official Debian repo for LizardFS, is a good addition to the solution.

**Comment by onlyjob** [comment]
> I see the "leeching" is a good thing, making Ubuntu a "faithful" (in the sense of package collection) descendant of Debian.

Well if you don't mind 98+% of unsupported/unmaintained packages... Ubuntu only support ~2000 packages and most of the remaining packages are taken care of in Debian only. Besides derivatives introduce delays in propagation of fixes (both ways) and take you further away from the source of knowledge.
As for added value, I don't recognise any in Ubuntu so IMHO the trade-off of installing derivatives is usually not in favour of users...

**Comment by 19wolf** [comment]
So question;
I installed `3.12.0` (Ubuntu) from packages.lizardfs.com and it uses `mfs:mfs` as the user and `/var/lib/mfs` and `/etc/mfs`, instead of `lizardfs:lizardfs` etc. But I then ran `apt upgrade` and it installed `3.12.0+dfsg-1` and now everything is looking for files in `/etc/lizardfs` and services are running as `lizardfs:lizardfs` and I just want to unify everything; How do I do that, and what do I unify it to?

**Comment by njhurst** [comment]
move everything to the user lizardfs:lizardfs.
