### ISSUE TITLE
Wishlist 5.x - NFSv4.1

### ISSUE THREAD

**Issue by Zorlin** [lizardfs/lizardfs#470]
Native support for NFSv4.1 would be a killer feature.

Ideally you would use [NFS-Ganesha](https://github.com/nfs-ganesha/nfs-ganesha) (thanks @cloudweavers) instead of writing a new NFS server from scratch - this would reduce duplication of effort and make the code easier to maintain.

**Comment by cloudweavers** [comment]
Instead of doing a full NFS server (yet another one!) I would support Ganesha ( https://github.com/nfs-ganesha/nfs-ganesha ) that is stable, extremely high performance and uses a modular adaptation layer that should be easy to use with Lizard (already supports Gluster, Ceph, ZFS and others)

**Comment by Zorlin** [comment]
@cloudweavers Excellent suggestion :) I've amended the original post.

**Comment by drauschenbach** [comment]
I recently spent a full day playing with nfs-ganesha with thoughts of front-ending a LizardFS cluster with it. I didn't get anything working... the NFS world is still a real mess due to the pre-v4 rpc/portmap legacy. Part of my problem is that I'm working with containers, because I think they're the only thing that matter!

From the container perspective, I see the the cluster manager communities actively working on FUSE support. For example, the proposed [Kubernetes Flex Volume API](https://github.com/kubernetes/kubernetes/issues/32543) would allow me to deploy a LizardFS Docker Volume Plugin to all nodes in the cluster as a DaemonSet. The volume plugin would be a simple REST endpoint wrapping `mfs.mount`.

Stuff like that will come together soon enough, and avoid the need for intermediary NFS gateways for the use cases that don't absolutely need it.

**Comment by pkali** [comment]
LizardFS 3.12 has got full pNFS and NFS 4.1support with Ganesha NFS plugin. It was not easy at all, but finally we are here!

Hook up your NFS clients to LizardFS and enjoy the convenience!
