### ISSUE TITLE
Unable to find expected entry 'main/binary-i386/Packages'

### ISSUE THREAD

**Issue by kinosang** [lizardfs/lizardfs#485]
I saw that you have removed i386 packages from your apt source, it causes an error about apt.

```
Unable to find expected entry 'main/binary-i386/Packages'
```

Use `deb [arch=amd64] http://packages.lizardfs.com/ubuntu/trusty trusty main` for Ubuntu trusty can fix it.

**Comment by pbeza** [comment]
Is it still an issue?

**Comment by kinosang** [comment]
@pbeza I don't know, we force the `arch=amd64` attribute in the source list files. Maybe someone can have a test.

**Comment by pbeza** [comment]
@kinosang I can clearly see that there is no package for `i386` architecture [in here](http://packages.lizardfs.com/ubuntu/trusty), but for sake of completeness can you please check what is the output of the following two commands?
1. `dpkg --print-architecture`
1. `dpkg --print-foreign-architectures`

BTW: out of curiosity – why don't you use [LizardFS package](https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=lizardfs) from official Ubuntu repository? Because of [old](https://wiki.ubuntu.com/Releases) `Ubuntu Trusty` which [seems to not have](https://packages.ubuntu.com/search?suite=trusty&searchon=names&keywords=lizardfs) it in its repo?

**Comment by kinosang** [comment]
@pbeza I just check the architectures, it seems okay.

Note: this issue is reported almost 3 years ago, now we use a minimal customized CentOS on new infrastructures, and we are eliminating old infrastructures which run Ubuntu 14.04
