### ISSUE TITLE
3.10.2: makesnapshot performance regression

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#490]
3.10.2 is affected by yet another performance regression that was mentioned on #475. Before 3.10.2 nightly script to take snapshots used to take minutes to finish but on 3.10.2 (with latest commits to fix poor performance of _settrashtime_ and _setgoal_) snapshotting takes 10+ hours and all this time master uses 100% CPU and barely responds to any requests making the whole cluster unusable for 10+ hours...

**Comment by MPaszkiewicz** [comment]
Did you try using snapshots with commits 2716, 2717, 2718?

**Comment by onlyjob** [comment]
No, not yet... How would I learn about those changes without you telling me? I hope those changes will be released ASAP -- they are much needed to fix numerous regressions of 3.10.2...

**Comment by onlyjob** [comment]
Fixed in 3.10.4 though removing large snapshot still uses nearly 100% CPU on master...
Thanks.

**Comment by psarna** [comment]
Just to clarify: master uses nearly 100% of CPU, because it has something to do (i.e. creating a large snapshot). Still, if any clients/other requests were to appear, they would be served with equal priority - creating a snapshot would then occupy, let's say, 33% CPU only. So, in my opinion, using 100% of CPU when it's not needed for anything else anyway is just good utilization ;)

The new design of handling large operations is more complex, so it takes more time than before to create the same snapshot, but it is still infinitely times better to have high CPU utilization for 10 minutes and still serve clients just as before than to have a totally unresponsive master for 2 minutes...
