### ISSUE TITLE
trouble with replacing disks, cluster very unstable

### ISSUE THREAD

**Issue by biocyberman** [lizardfs/lizardfs#516]
I moved 4X3TB hard drives from chunkserver2 to chunkserver1, which is also a master and already has one copy of data on other existing disks there. I then put 4x4TB new hard disks onto chunkserver2. 

Two things are happening: One, the cluster wants to copy data back to chunkserver2. The disk usages of the 3TB drives on chunkserver1 now drops to less than 10%, where before moving they are 99%.  And two, it already deletes duplicate or invalid duplicated/overgoal chunks on chunkserver1. The result is that the cluster is very slow and emits tons of messages in /var/log/syslog (Ubuntu 14.04) like the following: 

```
chunkserver1 mfsmaster[27557]: chunk 00000000001DCEF4_00000002 - invalid copy on (10.2.70.25 - ver:00000003)
chunkserver1 mfsmaster[27557]: (10.2.75.5:9422) chunk: 00000000001EACF4 replication status: Unknown LizardFS error
chunkserver1 mfsmaster[27557]: chunk 00000000001DCA20 has only invalid copies (1) - please repair it manually
chunkserver1 mfsmaster[27557]: chunk 00000000001DCA20_00000002 - invalid copy on (10.2.70.25 - ver:00000003)
chunkserver1 mfsmaster[27557]: chunk 00000000001DCA1F has only invalid copies (1) - please repair it manually
chunkserver1 mfsmaster[27557]: chunk 00000000001DCA1F_00000002 - invalid copy on (10.2.70.25 - ver:00000003)
chunkserver1 mfsmaster[27557]: (10.2.75.5:9422) chunk: 00000000002345F0 replication status: Unknown LizardFS error
chunkserver1 mfsmaster[27557]: (10.2.75.5:9422) chunk: 00000000001DA9ED replication status: Unknown LizardFS error
chunkserver1 mfsmaster[27557]: (10.2.75.5:9422) chunk: 00000000001DAA75 replication status: Unknown LizardFS error
chunkserver1 mfsmaster[27557]: (10.2.75.5:9422) chunk: 00000000001DAFB1 replication status: Unknown LizardFS error
```

How do I make the chunks on chunkserver1 valid again? 
And since I see about 80.000 chunks on the clusters are waiting to be deleted. I get scared of losing data so I shut down the cluster now. How to be sure that LSF does not delete something I would regret?

**Comment by cypromis** [comment]
You cannot just take out harddisks from one chunkserver and stick them into another chunkserver that is already active unless you want to empty out one set of disks. The chunkserver will think it has two versions of chunks and will erase all chunks that seem to be from an old version. It will then try to create fresh replicas on a different chunkserver according to the set goal. This is precisely the expected behavior. Nothing weird about it. 
Why would you do something weird like putting disks from one chunkserver into a different one that already contains chunks from the same dataset in the first place?

**Comment by cypromis** [comment]
Also in what way is that related to the stability of the cluster?
