### ISSUE TITLE
create-deb-package.sh fails with LIZARDFS_OFFICIAL_BUILD: parameter not set

### ISSUE THREAD

**Issue by n-a-b-s-t-e-r** [lizardfs/lizardfs#531]
Hi,

I'm trying to update my lizardfs and the configure part fails.  Is there something that I need to do or is it a problem with the script?  

The last part of the error is below:

 dpkg-source -b lizardfs
dpkg-source: info: using source format `3.0 (native)'
dpkg-source: info: building lizardfs in lizardfs_3.11.0.tar.xz
dpkg-source: info: building lizardfs in lizardfs_3.11.0.dsc
 debian/rules build
dh build --with systemd
   dh_testdir
   debian/rules override_dh_auto_configure
make[1]: Entering directory '/tmp/lizardfs_deb_working_directory/lizardfs'
./configure --with-doc
./configure: 19: ./configure: LIZARDFS_OFFICIAL_BUILD: parameter not set
debian/rules:10: recipe for target 'override_dh_auto_configure' failed
make[1]: *** [override_dh_auto_configure] Error 2
make[1]: Leaving directory '/tmp/lizardfs_deb_working_directory/lizardfs'
debian/rules:25: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by psarna** [comment]
It's been a long time since someone other than our automatic build system used the script :)

A quick workaround is to run
~~~
export LIZARDFS_OFFICIAL_BUILD=NO
~~~
(or =YES, if you want the version to be 3.11.0 instead of 3.11.0-devel-{commit_hash_from_git}),
and then build again.

The script should work even without this variable set, so it is indeed a problem with the script. Someone will fix it soon (not today though, Sunday is not exactly office hours).

Also, we have a script for creating .deb packages in repo's root directory, you might want to use it instead of executing dpkg-source directly: https://github.com/lizardfs/lizardfs/blob/master/create-deb-package.sh

**Comment by n-a-b-s-t-e-r** [comment]
Thank you Piotr, `export LIZARDFS_OFFICIAL_BUILD=NO` does allow `./create-deb-package.sh` to run. I tried it last weekend (btw mine is only a hobby project on Banana and Raspberry Pis!).  Another error comes up during compilation, but I'll open another issue for that.  Look forward to `create-deb-package.sh` being updated.  :-)

**Comment by n-a-b-s-t-e-r** [comment]
Hi, this issue should be open until the `create-deb-package.sh` script is fixed.  Thanks.

**Comment by n-a-b-s-t-e-r** [comment]
Hello,

I would like to offer a very simple patch file which fixes this problem.

Regards.

[create-deb-package.sh.patch.txt](https://github.com/lizardfs/lizardfs/files/1032893/create-deb-package.sh.patch.txt)
