### ISSUE TITLE
Packaging for Fedora - Best config path

### ISSUE THREAD

**Issue by jdieter** [lizardfs/lizardfs#535]
I'm looking to package LizardFS for Fedora (current spec [here](https://www.lesbg.com/jdieter/lizardfs.spec), review request [here](https://bugzilla.redhat.com/show_bug.cgi?id=1441729)), and I have a question.

According to the [Debian Quickstart](https://docs.lizardfs.com/quickstart.html), the configuration path is /etc/lizardfs rather than /etc/mfs and local state is stored in /var/lib/lizardfs rather than /var/lib/mfs.  Since this is a new Fedora package, should I use the same paths?  Should I also create the user/group lizardfs.lizardfs rather than mfs.mfs?

(Also, if you have any comments or questions about my spec, please let me know in a comment on this issue)

**Comment by cypromis** [comment]
Just so you do not double my work ..
https://build.opensuse.org/project/show/home:cypromis:lizardfs

**Comment by cypromis** [comment]
Trying to get all the distros into ONE spec so that we do not have to maintain  more than ONE.

**Comment by jdieter** [comment]
I totally understand, but Fedora has [very specific guidelines](https://fedoraproject.org/wiki/Packaging:Guidelines) that have to be followed for it to be part of the Fedora repository, and some aspects of the spec, while perfectly valid in a 3rd-party repository, are blockers in Fedora.  (As some random examples, see [this guideline](https://fedoraproject.org/wiki/Packaging:Guidelines#File_Permissions) and it's strict limits on the use of %defattr, and [this requirement](https://fedoraproject.org/wiki/Packaging:Guidelines#Compiler_flags) that all packages use Fedora's default compiler flags.)

You'll note that I started with the spec packaged with LizardFS and have made only the changes necessary to follow the guidelines.

I do notice in your spec that you use /etc/mfs and /var/lib/mfs.  Are those then the canonical locations of these paths?

**Comment by cypromis** [comment]
I really appreciate your effort but I still would like to keep things in one place. With the amount of changes planned maintaining multiple spec files is something we will not be able to manage. A lot of work is going into creating one upstream specfile that would be usable by all distros and I am sure that we can adjust it so that it also adheres to fedoras requirements.
The spec currently packaged is going away, what I showed you is the integration work to make it cross platform.
We already have problems because of the disconnected way the official debian package is maintained it would really help if we could avoid more disconnection since there is no way we will be able to maintain that. If you would like to discuss, I would suggest we move this to the forum since its not really a bug :)

**Comment by jdieter** [comment]
Ok, I've [opened a topic](https://lizardfs.org/forum/thread/2/4/25/fedora-packaging#post74) on the forum, and I'll close this.
