### ISSUE TITLE
severals few chunkserver on the same machine 

### ISSUE THREAD

**Issue by Amarahtbase** [lizardfs/lizardfs#553]
Hello,

Can you help me , I would like to know if it's possible to use several chunserver inside the same machine? 
I have ssd and hdd disk on the same computer and I wanted to use only ssd for one purpose and hdd for other purpose.

thank you

**Comment by psarna** [comment]
1. Prepare another mfschunkserver.cfg file for the new chunkserver in a different path, let's call it `/etc/chunkserver2.cfg`
2. Prepare another mfshdd.cfg file for the new chunkserver in a different path, let's call it `/etc/hdd2.cfg`
3. Set HDD_CONF_FILENAME in chunkserver2.cfg file to the path of newly prepared mfshdd.cfg file, in this example `/etc/hdd2.cfg`
4. Set CSSERV_LISTEN_PORT to non-default, unused port (like 9522) in `/etc/chunkserver2.cfg`
5. Run the second chunkserver with `mfschunkserver -c /etc/chunkserver2.cfg`
6. Repeat if you need even more chunkservers on the same machine (not very recommended though)

P.S. If you need to run the second chunkserver as a service, not just daemonized process, then you'd have to prepare a simple systemd/init.d script yourself for now, there are no out-of-the-box solutions yet. If you do prepare something like this, feel free to contribute via a pull request.

**Comment by Amarahtbase** [comment]
Thank you very much

**Comment by ahnselina** [comment]
hi guys
I want to run multiple chunkservers on the same machine.
I followed the steps mentioned above(mfschunkserver -c /etc/chunkserver2.cfg...)， but I ran into a problem. There was the first mfschunkserver process, when I ran "mfschunkserver -c /etc/chunkserver2.cfg", the first mfschunkserver process(mfschunkserver start) disappeared.And I cannot figure out what's going on.
Is there any another steps to run multiple chunkservers on the same machine  besides the steps mentioned above?

**Comment by Zorlin** [comment]
Make sure you're running the chunkservers on different ports...

>

**Comment by ahnselina** [comment]
> Make sure you're running the chunkservers on different ports...
> […](#)
I had set the chunkservers listen on different ports, now the problem is:
once I start a new chunkserver process, the old chunkserver process exits.

the info of netstat -l as follows:

$ netstat -lp | grep mfs
tcp 0 0 0.0.0.0:9419 0.0.0.0:* LISTEN 15190/mfsmaster
tcp 0 0 0.0.0.0:9420 0.0.0.0:* LISTEN 15190/mfsmaster
tcp 0 0 0.0.0.0:9421 0.0.0.0:* LISTEN 15190/mfsmaster
tcp 0 0 0.0.0.0:9422 0.0.0.0:* LISTEN 16074/mfschunkserver
tcp 0 0 0.0.0.0:9424 0.0.0.0:* LISTEN 15190/mfsmaster

I start a new chunkserver listen to the port 9522 use cmd "mfschunkserver -c /etc/chunkserver2.cfg":

$ netstat -lp | grep mfs
tcp 0 0 0.0.0.0:9419 0.0.0.0:* LISTEN 15190/mfsmaster
tcp 0 0 0.0.0.0:9420 0.0.0.0:* LISTEN 15190/mfsmaster
tcp 0 0 0.0.0.0:9421 0.0.0.0:* LISTEN 15190/mfsmaster
tcp 0 0 0.0.0.0:9424 0.0.0.0:* LISTEN 15190/mfsmaster
tcp 0 0 0.0.0.0:9522 0.0.0.0:* LISTEN 6722/mfschunkserver

" ps -ef | grep mfschunkserver " only see the new chunkserver process, the old chunkserver process disappeared.
