### ISSUE TITLE
Documenation is incorrect

### ISSUE THREAD

**Issue by reschandreas** [lizardfs/lizardfs#562]
Under [https://docs.lizardfs.com/adminguide/replication.html?](url) it is recommended to use `lizardfs setgoal goal_name object` but when executing this i only get  `lizardfs: command not found`
but `mfsgetgoal goal_name object` works just fine, please fix this.

**Comment by psarna** [comment]
What version of LizardFS are you using? `mfssetgoal` is deprecated in favour of `lizardfs setgoal` for a long while now.

**Comment by psarna** [comment]
Nah, `lizardfs` is a part of lizardfs-client, it's just newer than `mfssetgoal` and other tools.

**Comment by reschandreas** [comment]
I installed `lizardfs` yesterday with apt

**Comment by psarna** [comment]
It still gives me very little information on what is your LizardFS version, but assuming that your OS is Ubuntu 16 and that you use official repositories, let's assume v3.9.4. All newer versions (higher or equal to 3.10.6) use `lizardfs setgoal` utility instead of `mfssetgoal` and that's why current documentation refers to `lizardfs setgoal`.

If you'd like to try the latest 3.11.2 release (to which documentation is always up-to-date), go to https://lizardfs.com/download/ or build LizardFS from source.

**Comment by reschandreas** [comment]
Sorry I'm not at work anymore, I'll tell you tomorrow. My Os is Mint and I added the repository that was considered in the documentation.

**Comment by matthiaz** [comment]
@reschandreas To check your version of lizardfs-master on Mint(or ubuntu) try something like 
dpkg -s lizardfs-client | grep Version

or on the master

dpkg -s lizardfs-client | grep Version

**Comment by reschandreas** [comment]
@psarna you were right, I got v3.9.4.
