### ISSUE TITLE
Does lizardfs have encryption?

### ISSUE THREAD

**Issue by Cyclic3** [lizardfs/lizardfs#566]
Is there any way of encrypting the data sent between the client and master? I had a go with wireshark, and managed to retrieve data sent to the server. Not only that, but any given password will send a constant value. I do not claim to be any form of crypto expert, but I am sure this could be used to gain access to a system.

**Comment by pkali** [comment]
Hi!
thanks for this important question!
In short - LizardFS is not intended to be used over public networks - its primary use case is driving a storage / computational cluster inside a well protected data centre. When links to foreign data centres are needed, adequately secured VPN should be used.

Security layer is planned, is has lower priority though due to its imminent and unavoidable effect of deteriorating the performance.

**Comment by Cyclic3** [comment]
Ok, thanks!

**Comment by styk-tv** [comment]
yes... it will be slower... therefore not a priority.... we can skip encryption...what a great mindset

**Comment by dsimic** [comment]
I would love to see this too. Setting up a VPN infrastructure is an extra hassle and extra admin overhead etc. It would be great if LizardFS could just use SSL over TCP it would make life a bit better.
