### ISSUE TITLE
Recovering Unavailable/Missing Chunks

### ISSUE THREAD

**Issue by matthiaz** [lizardfs/lizardfs#567]
I noticed this morning that I am missing 8 chunks. I am not entirely sure how it happened but I am currently more concerned with fixing it. 
I noticed at the bottom of mfs.cgi that it says 

> Important messages:
> 
> * currently unavailable file 1543879: datacontainer/files/data20130710/2077147
> * currently unavailable file 5738183: datacontainer/files/data20140521/01106/4710
> * currently unavailable file 14126791: datacontainer/files/data20140521/01587/2811
> 
The missing filenames are 20177147, 4710 and 2811. That's a bit confusing without a name or extension but bare with me... 

So I logged on to a client and ran:
`/mnt/lizardfs# mfscheckfile /mnt/lizardfs/datacontainer/files/data20130710/2077147
/mnt/lizardfs/datacontainer/files/data20130710/2077147:
 chunks with 1 copy:              1`

I also ran: 
/mnt/lizardfs# mfsfileinfo /mnt/lizardfs/datacontainer/files/data20130710/2077147
/mnt/lizardfs/datacontainer/files/data20130710/2077147:
        chunk 0: 0000000001917A18_00000001 / (id:26311192 ver:1)
                copy 1: 172.15.15.51:9422:_

So this means I actually have the file, right? So why does lizardfs indicate it as unavailable?

I happened to have a backup of those particular files because our migration from our old system isn't completed yet. I compared them using **diff**. The data in them is exactly the same. 

`/mnt/lizardfs# diff -s /mnt/lizardfs/.../2077147 /mnt/backupstuff/.../2077147 
Files /mnt/lizardfs/.../2077147 and /mnt/backupstuff/.../2077147 are identical`

Any idea what is going on? If there are missing chunks, and I copy over the originals, will new chunks be created? Or will the existing ones be inserted again?

**Comment by psarna** [comment]
1. Please provide your LizardFS version and OS version (it also applies to any future issues)
2. File checking loop is continuous and usually checks all the files every hour. It means that "Important messages" can present data from around an hour ago. If you checked with `lizardfs fileinfo` that the file exists, it means it exists and everything is fine. It probably went missing for a while (due to chunkserver restart or something like that), the file checking loop noticed it and written a report to "Important messages". The message will probably disappear soon.

**Comment by matthiaz** [comment]
@psarna Thanks for the quick reply. 

This was on ubuntu 16.10 with lizardfs 3.11.0

I'll check again in a few hours. Thanks for clarifying
