### ISSUE TITLE
EC chunks are not replicating

### ISSUE THREAD

**Issue by njhurst** [lizardfs/lizardfs#583]
I changed a bunch of low priority datasets to ec modes:
```
18	first_ec	first_ec: $ec(3,1) {rack rack rack rack}
19	second_ec	second_ec: $ec(5,2) {rack rack rack rack rack rack rack}
20	third_ec	third_ec: $ec(5,3) {rack rack rack rack rack rack rack rack}
```

but after a week none of them are safe:

```
Chunks availability state:
	Goal	Safe	Unsafe	Lost
	3	6195095	-	-
	first_ec	20810	-	-
	second_ec	725962	9	-
	third_ec	119210	-	-

Chunks replication state:
	Goal	0	1	2	3	4	5	6	7	8	9	10+
	3	6195095	-	-	-	-	-	-	-	-	-	-
	first_ec	-	-	20810	-	-	-	-	-	-	-	-
	second_ec	-	-	-	-	-	725970	1	-	-	-	-
	third_ec	-	-	-	-	-	-	119210	-	-	-	-

Chunks deletion state:
	Goal	0	1	2	3	4	5	6	7	8	9	10+
	3	6195095	-	-	-	-	-	-	-	-	-	-
	first_ec	-	-	8072	12017	363	355	3	-	-	-	-
	second_ec	-	-	-	-	86064	635691	4216	-	-	-	-
	third_ec	-	-	-	-	23571	95635	-	4	-	-	-
```

After an initial few days of enthusiastically moving data, lizard seems to have stopped doing any data transfer.  Is the system stuck, or am I misinterpreting the charts?  To start it I changed the dataset goals from 3 to one of those ec modes.  I have two machines/chunkservers with 7 drives each with the rack label, no drives are full, around 30% free space. 

The 9 lost chunks is also worrying, though the web interface instead shows 9 as endangered.

I'm running a mix of 3.10.4(ubuntu provided) and 3.10.6(built by hand)

**Comment by psarna** [comment]
Wait, two chunkservers? To completely fulfill goal 3 you need at least 3, and to fulfill ec(5, 3) you would need 8 distinct chunkservers. LizardFS will not create a copy of any chunk on the same chunkserver, even if the drive is different.

One way around it is to spawn more than 1 chunkserver on a physical machine (which can be done by providing another configuration file and launching the second chunkserver with `mfschunkserver -c /path/to/mfschunkserver-another-config.cfg start` or by virtualization), but generally a solution to your problem is running enough chunkservers to fulfill your goal definitions.

What probably happens in your installation now is LizardFS trying to create at least some ec parts of your goal definitions, but never succeeding, since there are no more chunkservers to create all needed copies. It would also explain why the web interface is having hard time understanding what happens.

**Comment by psarna** [comment]
Wait, two chunkservers? To completely fulfill goal 3 you need at least 3, and to fulfill ec(5, 3) you would need 8 distinct chunkservers. LizardFS will not create a copy of any chunk on the same chunkserver, even if the drive is different.

One way around it is to spawn more than 1 chunkserver on a physical machine (which can be done by providing another configuration file and launching the second chunkserver with `mfschunkserver -c /path/to/mfschunkserver-another-config.cfg start` or by virtualization), but generally a solution to your problem is running enough chunkservers to fulfill your goal definitions.

What probably happens in your installation now is LizardFS trying to create at least some ec parts of your goal definitions, but never succeeding, since there are no more chunkservers to create all needed copies. It would also explain why the web interface is having hard time understanding what happens.

**Comment by njhurst** [comment]
I woke up tonight realising exactly what you say here, and before I started on it I checked my email and you said the same thing :)

Here's what I did:  I made a separate `/etc/lizardfs/mfschunkserver$i.cfg` and  `/etc/lizardfs/mfshdd$i.cfg` along with the `/var/lib/lizardfs/lizard$i` for each drive `$i` and pointed a separate `/etc/systemd/system/lizardfs-chunkserver$i.service` to each one using `-c` as you suggest.  I enabled all of these new services and emptied out the original mfshdd and then started the new services.  My server tab is now huge, but as you predict, now I have a ton of chunk replications and the 'x to replicate' entries are falling fast.

Thanks for your advice, I think everything is good now, we can close this issue.

future feature requestion: allow some easier way to permit chunks on different drives than replicating all the chunkservers.
alternative feature requestion: provide some template way to specify the main configuration parameters to be shared across multiple chunkserver configurations (e.g. a `#include` for cfg)
