### ISSUE TITLE
Cannot removed reserved file

### ISSUE THREAD

**Issue by Blackpaw** [lizardfs/lizardfs#595]
I have one large file sitting in reserved (972 ec(2,1) chunks) that I cannot remove. All mounts have been remounted and a lsof|grep <filename> does not find it on any client.

`rm reserved/0000036D\|images\|301\|vm-301-disk-1.qcow2 
rm: cannot remove ‘reserved/0000036D|images|301|vm-301-disk-1.qcow2’: Permission denied`

It appears to be a left over from changing the entire volume from ec(2,1) to goal 3.

Thoughts?

**Comment by Blackpaw** [comment]
Resolved: Changed SESSION_SUSTAIN_TIME to 3600 (1 Hour) was 24 hours.

I must have had a session killed, that would take SESSION_SUSTAIN_TIME hours to resolve. Probably if I waited overnight it would have been ok.

**Comment by Zorlin** [comment]
Thanks for getting back to us with the resolution :+1:

**Comment by guestisp** [comment]
Why 24hours as default? Any advantage for this high timeout?

**Comment by psarna** [comment]
@guestisp 
24 hours is a legacy setting, we just never changed that.

**Comment by guestisp** [comment]
But, what was the advantage for this high setting?
Was set as 24 hours for what?

What's the suggested value currently?

**Comment by psarna** [comment]
@guestisp 
I don't know the original idea, but it was most likely something like that:
1. From sysadmin point of view it's probably nice to have 24 hours to fix something and restore your session.
2. Potentially having some reserved files for 24 hours is usually not a problem at all.

The suggested value is leaving the default. If you expect a high number of broken sessions and reserved files in your installation (due to hardware reasons or something like that), free to adjust your SESSION_SUSTAIN_TIME setting.

**Comment by Blackpaw** [comment]
I presume this only comes into play when a session is disconnected due to network issues, i.e the mfsmount is still active and can reconnect when the network is fixed.

Not something that comes up often, but easy enough to shrink the default.

**Comment by 4Dolio** [comment]
The reserved files feature actually came in handy during an incident with a badly behaving script.  It unexpectedly removed with 0 trash time all files. Which lfs happily complied with, and even purged all relivent chunks, except those locked in reserved due to the service utilizing them still having them locked.  So after some clever metadata changelog editing out of those fatal delete operations, and the metadatarestore of that into new rolled back metadata.  And poof, the critically needed chunks having been preserved by reserved and locking and now masters thinking all files still exist.  Everything not locked was lost and in a very sad looking chunk health map, but the active service data lived on to serve another day... so, thanks for great reserved and trash inode handling.
