### ISSUE TITLE
metadata server protocol

### ISSUE THREAD

**Issue by guestisp** [lizardfs/lizardfs#621]
How can I know if current metadata server is master or shadow ? I need to ask directly to the server, without calling external commands.

Can I send a defined packet to metadata port ?

**Comment by psarna** [comment]
Yes, `lizardfs-admin metadataserver-status` returns exactly that. Just take the packet definition from its source code, https://github.com/lizardfs/lizardfs/blob/master/src/admin/metadataserver_status_command.cc

**Comment by guestisp** [comment]
Uhm, i'll try.
Do you have any example by using curl or similiar ?

**Comment by psarna** [comment]
curl is as much a tool as lizardfs-admin. I have a bash example at hand:
~~~
echo -n 00000609000000080000000000000000000000000 | xxd -r -p | nc localhost 9421
~~~
Reply is in binary format of `msgid:32 serverstatus:8 metadataversion:64`
Status is 1 if it's master, 2 if connected shadow, 3 if disconnected shadow.

**Comment by guestisp** [comment]
Great.
But, what is this: `00000609000000080000000000000000000000000` ?

**Comment by psarna** [comment]
That's a "metadataserver-status" packet presented in hex, you can just send this to master over TCP and you'll get your reply. Its contents are described in source code, see my first reply.

**Comment by guestisp** [comment]
Ok but i'm having some trouble to convert the bin output coming from the command, to `msgid:32 serverstatus:8 metadataversion:64`

**Comment by guestisp** [comment]
Something doesn't work as expect. Is the output, the binary encoded version of string `msgid:32 serverstatus:8 metadataversion:64` ? If yes, it should be very long.

This is what I get:

`0000060a000000110000000000000000010000000000000001`

by using:

```
<?php
$sock = fsockopen('localhost', 9421);
fwrite($sock, pack('H*', '00000609000000080000000000000000000000000'));

$response = fread($sock,1024);

echo bin2hex($response);

fclose($sock);
```

**Comment by psarna** [comment]
It will make sense if you interpret :32 as 32 bits, not bytes.

**Comment by guestisp** [comment]
Currently I'm not interpreting anything
I've posted the full output code, but I don't know how lizard works, thus I don't know if `0000060a000000110000000000000000010000000000000001` is something that makes sense

Do you have a bash code that will parse the output in addition to the posted one that only send command but doesn't wrote anything readable as output?

I'm really close to finish our HA failover procedure but I have to directly talk to lizard via php/bash

**Comment by psarna** [comment]
Not right now, but you basically already have the answer.
The response you get in your code can be interpreted as:
~~~
0000060a000000110000000000000000010000000000000001
[0000060a] [00000011] [00000000] [00000000]  metadataserver status right here ----> [01] <-- [0000000000000001]
~~~

**Comment by guestisp** [comment]
Ok now it's clear.

**Comment by guestisp** [comment]
And what about the request? How can I get `00000609000000080000000000000000000000000` from 1545 that should be the command id (as 1546, 060a in hex, is the response id)

**Comment by Blackpaw** [comment]
What was wrong with just using lizardfs-admin

**Comment by guestisp** [comment]
I'm developing a tool that should not require any external software

**Comment by guestisp** [comment]
I also need some details about request/response for triggering metadata promotion from shadow to master

**Comment by guestisp** [comment]
Any hint? I'm still stick at communicating with metadata server from a PHP script (probably in the near future I'll replace everything in Go)

**Comment by psarna** [comment]
~~~
lizardfs-admin promote-shadow
Expected <shadow ip> and <shadow port> for promote-shadow
Usage:
    lizardfs-admin COMMAND [OPTIONS...] [ARGUMENTS...]

promote-shadow <shadow ip> <shadow port>
    Promotes metadata server. Works only if personality 'ha-cluster-managed'is used.
    Authentication with the admin password is required.
~~~
So, go to admin/promote_shadow_command.cc in source code, get the packet information and, if you really need to, send them directly from your script just like the previous command.

This one is trickier though, because promote-shadow command requires a password, so there's a challenge-response mechanism before you can actually send the request. The easiest method is to use `lizardfs-admin`, this time I don't have any magic bash lines at hand and it would take way too much work to prepare it.

**Comment by guestisp** [comment]
The issue is how to parse the output. I've tried almost any `unpack` combinations, with no success. I'm able to read some fields, but not some other:

```
# php /tmp/test.php 
Array
(
    [number] => 1546
    [len] => 17
    [a] => 0
    [b] => 0
    [c] => 360287970189639681
)
```
this is with `unpack('Nnumber/Nlen/La/Lb/Qc', $response)`


```
# php /tmp/prova.php 
Array
(
    [number] => 1546
    [len] => 17
    [a] => 0
    [b] => 0
    [c] => 1
)
```
this is with `unpack('Nnumber/Nlen/La/Lb/Lc', $response)`


Your python script is using "Q" for unsigned long long but this doesn' seem to work properly in php because i don't know which data shoul I expect. I'm unable to check if returned data are OK or not.

**Comment by 4Dolio** [comment]
Why won't `exec( lizardfs-admin metadataserver-status --porcelain localhost 9421 | cut -f3 )` work?  LizardFS itself is an "external software" in and of itself, and lizardfs-admin is the tool provided to do the various things you are attempting to do, so why the resistance to using the tool provided?

**Comment by guestisp** [comment]
Because I need administative command on all nodes, even where a mount is required

I really don't like to put lizardfs-admin on a Xen host or similar, and , more over, what I'm trying to create is something that doesn't depends on anything. A single executable files without any dependency, wrote in Go. One of the main advantage of Go is the self contained executable. If you need external software, you'll loose one of the biggest advantage

**Comment by 4Dolio** [comment]
I do not follow "administative command on all nodes, even where a mount is required".  I do not understand what that means...

You only need to manage the master/shadow services on nodes which run that service.
You can treat Chunk Services, Meta Loggers, and Clients as completely separate entities/services.

So on master nodes you need:
* The master service packages.
* The lizardfs-admin packages.
* Whatever HA solution you use/develope (and it can be a singular binary/script)
** But it will NEED to interact with:
** 1. The master service. &
** 2. the lizardfs-admin (because that is how you talk to the master services)

Given that, What am I missing which  you are trying to accomplish?

**Comment by guestisp** [comment]
In fact, I don't need lizardfs admin on the clients. I was thinking to something else when writing

**Comment by 4Dolio** [comment]
Right.. You only need the admin stuff where the masters are.  It is only it's own (optional) package because it is only needed if you intend to do HA.. If you are not doing HA, then you probably do not really NEED to ask your master these types of questions.  But if you are doing HA, then you likely need to ask your master about what state it is in every couple of seconds, thus the tool with which to do that...

So.. Did we change your mind? You will use lizardfs-admin now??

**Comment by guestisp** [comment]
> So.. Did we change your mind? You will use lizardfs-admin now??

No. I still prefere to avoid any external deps. As wrote, is nonsense to make a Go application that requires external components where the language itself is self-contained and portable.

**Comment by 4Dolio** [comment]
PS. My corosync probes my master node once per second.  It probes my shadow nodes ever 2 seconds. All friggin day long "hay, you still the master, master?" ... "Hay master, what version you at now?" .. "and now?"  over and over and over, forever and ever... .oO( It could probably ask less often, I just never de-tuned it )

**Comment by 4Dolio** [comment]
auhhh... But the master service itself is an "external dep".. What if the lizardfs-admin were just an option for the lizardfs-master binary?  Would it still be an external dep?
Like: `lizardfs-master -poll "whatever the lizardfs-admin does now"` , would that change anything?

**Comment by guestisp** [comment]
> PS. My corosync probes my master node once per second. It probes my shadow nodes ever 2 seconds. All friggin day long "hay, you still the master, master?" ... "Hay master, what version you at now?" .. "and now?" over and over and over, forever and ever... .oO( It could probably ask less often, I just never de-tuned it )

Me too but in a different way.

> auhhh... But the master service itself is an "external dep".. What if the lizardfs-admin were just an option for the lizardfs-master binary? Would it still be an external dep?

Are you serious ? lizardfs-master binary is the software that you need to run. You can't consider that as an external dep. That's the main software, everything else is an external dep.

**Comment by guestisp** [comment]
> What if the lizardfs-admin were just an option for the lizardfs-master binary? Would it still be an external dep?

That would be ok. As you don't have to install anything more than the required binary. You need the master binary to run the master, and you don't need anything else. lizardfs-admin is an optional tool. I don't want to craete an orchestrator relying on optional tool, where master has a public protocol available.

The question isn't why I don't want to use external dep, but why master protocol isn't decribed somewhere, in an opensource software. I've asked how to encode the request and how to decode returned output and the only responses where "look through sources". Not exactly good responses for open source software. Try to do the same questions on Gluster or Ceph communities. You'll end up with detailed responses, because there is nothing to hide. Lizard Master seems to be a mysterious software

**Comment by 4Dolio** [comment]
.. well then, the solution is easy.. lizardfs-admin is NOT an optional tool... It is as important as the lizardfs-master binary itself... It just does not happen to be build into the master service (perhaps for master optimization reasons?)... So.. Just imagine that lizardfs-admin is a prerequisite of lizardfs-master and everything will be awesome!

As for the nature of the lfs community and source code and comments/documentation.. IDK what to tell you.. I am just a user... I run lizardfs-admin --help and futs around with it all until it does what I want.. I agree, the documentation could use more elaboration..  I suppose you could convert the lizardfs-admin tool in it's entirety into GO, or merge it into the master service source.. But I think just using the lizardfs-admin tool as is will be the path of least resistance... if that binary were a part of the main master service perhaps we would not be having this discussion?  It is what it is....

**Comment by guestisp** [comment]
> .. well then, the solution is easy.. lizardfs-admin is NOT an optional tool... It is as important as the lizardfs-master binary itself... It just does not happen to be build into the master service (perhaps for master optimization reasons?)... So.. Just imagine that lizardfs-admin is a prerequisite of lizardfs-master and everything will be awesome!

Ok, are you jocking. Please be serius.

**Comment by 4Dolio** [comment]
Sometimes I wonder that myself..  ( if you or if I are joking about any given thing )

I do not understand why you can not accept that lizardfs-admin is in fact a critical part of the lizardfs-master service, if you are implementing HA.  In such a situation lizardfs-admin is not at all optional, it is in fact required.  Without it you can not poll the master service for it's current state.

I wonder if you are not in fact punking all of us here by insisting that you re-implement lizardfs-admin in raw php or go when you have at your disposal the lizardfs-admin tool.  Which only exists for you to interact with a master service in an HA environment so to orchestrate said HA system.  So you see my friend, It is by no means optional...  It is only optional in the sense that if you run a master+CS on a Raspberry Pi, and you have no intention of doing any HA, then you do not need lizardfs-admin.  Seeing as how you are attempting to create a HA solution, you in fact NEED to use the lizardfs-admin tool.  That is why it exists.

So... Are you joking? or are you serious?

**Comment by guestisp** [comment]
> Without it you can not poll the master service for it's current state.
That's not true. There is a master protocol, i'm trying to see how this protocol works.
What's the problem ? Is the master protocol something that must not be used and must not be disclosed ?

I'm not re-implementing lizardfs-admin, i just need to execute only 3 commands: `metadataserver-status`, `promote-shadow`, `stop-master-without-saving-metadata`

And no, `lizardfs-admin` isn't mandatory for HA. There isn't any HA in LizardFS, the only HA implementation (if any) is a commercial product, there are no docs about any native HA system. 
Thus, you can't say that `lizardfs-admin` is mandatory for a feature that doesn't exist at all.

If you don't like that i'm trying to create a custom HA solution, please don't respond and dont hijack this issue. This isssue is for some explanations about the master protocol, if you are unable to explain what i'm asking for or if you are thinking different than me, please do not respond.

**Comment by Blackpaw** [comment]
I presume  guestisp want to query master status from devices that don't have lizardfs installed

**Comment by 4Dolio** [comment]
HA is not easy.
There are many ways to implement HA.
I appreciate the fact that LizardFS does not try to solve HA in one specific way as a core part of the free and open source set of discrete component services which as a whole delivers an amazingly versatile storage solutions.
I feel it is acceptable for the LizardFS team to make a profit selling their own specific method for solving HA, again, HA is difficult, perhaps more so than the individual lfs components which alone provide nothing of any usefulness.
MooseFS HA solution is not the same as LizardFS.
As I understand it MFS uses a shifting DNS handoff method while LFS uses a floating IP handoff method.
Both are very different and equally valid with each their own advantages and disadvantages.
We have many operators who use completely unique methods for implementing HA, Corosync, CARP, uraft, Consul+raft, php?, go?, etc...

Heck we could probably make a firewall manage it. I do not even use any of the crazy corosync+pacemaker features.  So I could probably just write something in bash to poll with lizardfs-admin and dump results into on a case statement, get all the members to vote or race, and then use lizardfs-admin to ask the members to do actions like quick stop, promote, stop, start as a master, start as a shadow, etc, etc.. THAT IS WHAT lizardfs-admin is for, it is your interface to your HA system, no mater what that system might happen to be... Because HA is hard, and there is value in letting us all find unique and novel ways to solve that part of this thing we call storage. 

> I presume guestisp want to query master status from devices that don't have lizardfs installed

Yes.. And that is fine, the source for lizardfs-admin is there.  I am sorry it does now have rich pseudo code comments or documentation, but it has --help which is reasonable... So we all <s>have resorted to</s> using it.  Sigh, good night. -- Peace and Love all

**Comment by 4Dolio** [comment]
A master alone does nothing
A chunk service alone will store store no bits.
A logger has no one to follow.
A client has no one to ask.
A tapecli can stream nothing to tape alone.
Perhaps a master alone could be an inode database, yet a client is needed to do that.
lizardfs-admin is how you make masters dance with each other, without it everyone just sits in their corners and things are just boring and chaperones have to gently show everyone the steps, and who has time for that?  ~~Dolio

**Comment by guestisp** [comment]
> I presume guestisp wants to query master status from devices that don't have lizardfs installed

Exactly

**Comment by 4Dolio** [comment]
>> I presume guestisp wants to query master status from devices that don't have lizardfs installed
> Exactly

What now... Why do you need to do that from anything except for the masters?  Wouldn't you also run the separate service of the cgi server?  Why shun the admin tool in order to execute HA, on masters, where you have cgi also?

**Comment by 4Dolio** [comment]
.. Heck, the cgi might be another good place to look for clues as to alternate methods for polling the master, or chunk services, since that is what that optional component does, in python I believe...

**Comment by guestisp** [comment]
Really, please stop
Stop asking WHY I have to do so, this issue is for HOW to communicate with master.
I'm not interested in using lizardfs-admin and I don't have to justify this to you so STOP.

Are you able to provide useful responses? Then reply with something useful. In other case, please stop to hijack every issue that I open.

Your behavior is very similar to a troll

**Comment by pkali** [comment]
OK, closing as right now all available solutions were already described in the thread. 
We are now working hard on delivering the new release with, among others, aforementioned (p)NFS support, with important media performance enhancements development following. Therefore we can not focus on small files. Our team does have some breakthrough ideas on improving small files performance, but this must be postponed.
