### ISSUE TITLE
3.12.0-rc

### ISSUE THREAD

**Issue by guestisp** [lizardfs/lizardfs#632]
I've seen the release notes about 3.12.0-rc.

Two major features:

- C API
- nfs-ganesha plugin

So, starting from 3.12, mfsmount will skip the whole FUSE stack and directly communicate with LizardFS ?

And what about nfs-ganesha ? Even nfs-ganesha is directly connected without FUSE ?

If yes, this is a huge improvements. Can't wait for an official release.
Did you make some performance comparison between FUSE and native connections ?

**Comment by psarna** [comment]
mfsmount practically **is** fuse, so it's not going to change. C API means that you can develop your own applications and use, say, lizardfs_read() function instead of read() system call, which would go directly to master/chunkservers instead of taking a kernel route via FUSE first.

nfs-ganesha is built on top of our C API, so it is directly connected to LizardFS clusters without FUSE.

**Comment by Blackpaw** [comment]
Very big step forward, especially for VM hosting usecase. Look fwd to testing Piotr.

**Comment by guestisp** [comment]
> Very big step forward, especially for VM hosting usecase. Look fwd to testing Piotr.
Totally agree. Awesome release.

> mfsmount practically is fuse, so it's not going to change

Don't you have plan to build a native client without FUSE and without the need to use NFS ?

**Comment by psarna** [comment]
That would pretty much mean developing our own kernel driver. As much as I like doing that, it's definitely not on a roadmap right now for a variety of reasons. FUSE works well enough, drivers are harder to maintain and it would take a lot of valuable time to produce one. Right now we have a ton of priorities other than a native driver.
Still, any plugins like nfs-ganesha can now benefit from C API direct communication. And if you need full file system capabilities - use the fuse-based client.

**Comment by Blackpaw** [comment]
>plugins like nfs-ganesha can now benefit from C API direct communication.

That was what I was intrigued with. And I believe you were doing a qemu block interface like rbd has? Trouble is those take a while to get through into system packages. Qemu really should have exposed a block plugin api.

**Comment by guestisp** [comment]
> That would pretty much mean developing our own kernel driver. 

You are right, my mistake. Even gluster native client is FUSE-based.

@Blackpaw anticipated me, I was referring to a native qemu block driver (like gluster, ceph and sheepdog) able to talk to Lizard directly.

I think they are here:
https://github.com/qemu/qemu/blob/master/block/gluster.c
https://github.com/qemu/qemu/blob/master/block/rbd.c
https://github.com/qemu/qemu/blob/master/block/sheepdog.c

**Comment by blink69** [comment]
yep, we also work on qemu, we got some PoC, but this needed much more work to do from us and right now is not on current roadmap. So you need to wait or order that functionality from us.

**Comment by guestisp** [comment]
Ok.
Anyway, this is a huge step forward, NFS support is awesome for any users forced to use NFS as the only shared storage supported

**Comment by eriklindahl** [comment]
Just out of curiosity, how will the the NFS-ganesha communication work? I guess the clients won't be able to talk directly to the chunkservers (since NFS-ganesha isn't aware of EC/XOR/duplication), so will it send all traffic through the metadata server or some other gateway, which then distributes it according to LizardFS storage layouts?

**Comment by Blackpaw** [comment]
Since NFS-ganesha will be using the new Lizardfs client library I imagine it will work the same as mfsmount - connect to mfsmaster for meta info and write directly to the chunkservers.

**Comment by psarna** [comment]
@eriklindahl 
That's a valid concern. Clients will generally read/write directly to the chunkservers. Only EC/XOR is slightly more complicated, but it still involves chunkservers only - EC parts go to one of the chunkservers, and this server indeed acts as a "gateway" and distributes other parts to other servers.

**Comment by psarna** [comment]
And, if your clients support pNFS (our plugin has pNFS support), duplication would go straight to chunkservers as well.

**Comment by guestisp** [comment]
So, client will directly talk to each chunkserver in parallel or writes are the same as mfsmount? (Write to one chunkserver, then this chunkserver will replicate to another one and so on)

**Comment by psarna** [comment]
With ganesha, there are 2 stages - NFS client and our plugin. What NFS client does is up to NFS - 3.0 and 4.0 would just write to one point, while pNFS will distribute to data nodes (which could also be chunkservers).

Then, after this first stage, data is processed by our plugin, which works exactly like before, because it's the same code. So, regular goal writes would be chained, ec goal writes would be parallel.

**Comment by kubikrobert** [comment]
Hello!
Any ETA fot the deb/yum packaged to be available?

I hope the NFS/pNFS plugin will help with my performance issue described in https://github.com/lizardfs/lizardfs/issues/635

**Comment by blink69** [comment]
Here you go http://packages.lizardfs.com/pkg/

**Comment by kubikrobert** [comment]
Thanks! Any documentation available regarding NFS plugin? How to use it, how it works?

**Comment by cypromis** [comment]
Should show up in the next couple of days in the documentation.

**Comment by guestisp** [comment]
Great!
