### ISSUE TITLE
when will the lizardfs-uraft release

### ISSUE THREAD

**Issue by lzslbd** [lizardfs/lizardfs#634]
I am looking forward to the lizardfs HA implemented by uraft, it is said to be released in 3.12.0. I am wondering when will it come out?

**Comment by guestisp** [comment]
It won't be released. It is their main commercial product

I'm working on an alternative RAFT implementation based on Consul

**Comment by Zorlin** [comment]
@guestisp Actually no, they have committed to releasing it (or a similar solution) in a few versions time. Kinda surprising but there you go.

**Comment by guestisp** [comment]
But some days ago I was contacted by skytechnolgy and I don't think they will release HA sooner as they told me it is the only commercial product that they sell and they use to pay their employees. I had a chat with one of their employees that told me this.

I've proposed a different HA implementation and they asked me many thousand euros to develop something that is more or less already implemented and planned to be realeased

So, why ask many thousand euros for something that would be made open source?

Feel free to correct me but I don't think HA would be released sooner

**Comment by blink69** [comment]
:) heh, I will leave some comment and close this issue.

Its not true that HA is our only commercial product, even if we want release everything on open licence (which is not trivial, incompatibility of different type of licence, also using 3rd party commercial library that is incompatible with GPL) we got customer base that will pay us for supporting their installations.

Regarding your question to implement Consul into LizardFS you got our price for develop new HA solution and maintaining that in main repository, Of course  you can disagree with our estimation and price. 

And once again I want to confirm rumor that uraft or other solution implemented directly in master will be published as a open source :)

Thank you

**Comment by guestisp** [comment]
> Its not true that HA is our only commercial product, even if we want release everything on open licence (which is not trivial, incompatibility of different type of licence, also using 3rd party commercial library that is incompatible with GPL) we got customer base that will pay us for supporting their installations.

This is exactly the opposite someone from your company told me via chat

The main reason for NOT publish the official HA was because it's your commercial product and you had experience that release something as opensource won't allow you to sell support .

I've suggested you to sell paid advanced support (like all company does when involved in open source product) and you told me you had a different experience: all users would use the open version and no one is interested in support when cluster is up and running, that's why your HA is a paid feature

This is what you told me. I don't think Hangout stored the chat history somewhere or I could publish what you told me.....

**Comment by blink69** [comment]
Ok, we will not go this direction just close this conversation, till I'm on current position will be as I say :P
