### ISSUE TITLE
Performance degradation from secondary group registration commits

### ISSUE THREAD

**Issue by eriklindahl** [lizardfs/lizardfs#660]
Hi,

When comparing performance between 3.10.4 and 3.12.0, I noticed that the old version had 20-25% better performance for small files (10Gb ethernet, writing to multiple SSD chunkservers).

After debugging, I managed to isolated it entirely to the client, and after a bit of git bisect it turns out this is due to the secondary group registration introduced with commits bb411c & 72e18b.

**Comment by eriklindahl** [comment]
Update: The slow part appears to be the call to FUSE function fuse_req_getgroups() from updateGroupsForContext() in src/mount/fuse/mfs_fuse.cc.

**Comment by eriklindahl** [comment]
I might have a hack fix that can be further refined. The problem seems to be that the routine updateGroupsForContext is called every time we want to get a context for the many functions in src/fuse/mfs_fuse.cc. That in turn calls fuse_req_getgroups(), which is implemented by reading in text files from the /proc filesystem and parsing ascii. This leads to a very large overhead for small files on fast networks.

To work around it, I used the existing cache classes and also hacked up a small cache for the Linux group lookups based on the uid that keeps the data for 1 second. It will likely only work on Linux with reasonably modern GLIBC, and it should be cleaned up to make the timeout a parameter, but it does seem to work: I get almost 30% better write performance for lots of small files, and the secondary group mechanisms appear to work just as before.

[CacheLinuxGroupLookups.txt](https://github.com/lizardfs/lizardfs/files/1727315/CacheLinuxGroupLookups.txt)

**Comment by psarna** [comment]
You're right, it is about fuse_req_getgroups() and we were aware of that. It may be a performance issue for lots of small files, like your case.

Your patch addresses the issue quite neatly, we will discuss it internally and see if that's how we want to fix it.

So, thanks for pointing out the issue and providing the patch, I'll come back with updates soon.

**Comment by psarna** [comment]
Under review here: http://cr.skytechnology.pl:8081/#/c/3257/

**Comment by eriklindahl** [comment]
Thanks for the patch Piotr! Unfortunately I seem to get a bunch of write permission errors with your patch that I don't get with mine; it creates directories fine, but then those directories have "nogroup" as group instead if my primary group.

**Comment by psarna** [comment]
Ah yes, it's still work-in-progress now, I just published the review link
for everyone to see (and it doesn't pass our test suite yet, exactly due to
the problem you described). We just decided to make the solution a little
bit more aware of things like changing groups of the process while it
operates, which makes it more complex. Also, we cannot extract group set
from uid, pid must be the key here. Still, the patch will be heavily based
on your code, huge thanks for that.

On Feb 23, 2018 21:03, "Erik Lindahl" <notifications@github.com> wrote:

Thanks for the patch Piotr! Unfortunately I seem to get a bunch of write
permission errors with your patch that I don't get with mine; it creates
directories fine, but then those directories have "nogroup" as group
instead if my primary group.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/lizardfs/lizardfs/issues/660#issuecomment-368123815>,
or mute the thread

**Comment by psarna** [comment]
@eriklindahl 
Ok, it's way more ready now, still undergoing review and tests, but it already passed a lot of them. If you'd like to test it as well, it would be very helpful. Also, since it's based on your work, I also set you as the official author of this commit. Please let me know if a) you'd prefer not to be mentioned for any reason, b) you'd prefer some of the info to be changed (like e-mail address). Just look at the "Author: " field in http://cr.skytechnology.pl:8081/#/c/3257/ for details.

**Comment by eriklindahl** [comment]
Sorry for taking some time, busy travel schedule this week! I finally had a chance to test things (also in combination with 95844d to reduce secondary group lookups), and both of them now seem to work great in our environment. Thanks a lot! This was just a *very* minor fix that mostly used stuff you had already written, but I'd be flattered to have my name in a LizardFS change - hopefully not the last one ;-)
