### ISSUE TITLE
May I move disks?

### ISSUE THREAD

**Issue by smurfix** [lizardfs/lizardfs#696]
I have one chunk server which is about to fail. Is it OK to just shut it down, move the disks to another chunk server, mount them, add them to mfshdd.cfg, and reload the chunkserver?

**Comment by smurfix** [comment]
Thanks.

**Comment by onlyjob** [comment]
Just plugging other chunkserver's HDD to a chunkserver may produce undergoal files and endanger data. This is because one chunkserver can only have one replica. When you add HDD with existing chunks they will be scanned and _deleted_ immediately if same chunk copy is found on other HDD(s).
See #502 for details.

It might be safer to allow data to replicate before plugging back HDD to another chunkserver or to connect it to temporary/dedicated chunkserver until no undergoal chunks are left.
