### ISSUE TITLE
lizardfs-ha-master.service missing in 3.13RC1

### ISSUE THREAD

**Issue by Blackpaw** [lizardfs/lizardfs#719]
Testing 3.13rc1 HA following the guide here:
  https://docs.lizardfs.com/adminguide/advanced_configuration.html#lizardfs-ha-cluster

Get as far as starting the uraft service

```
systemctl start lizardfs-uraft.service
Failed to start lizardfs-uraft.service: Unit lizardfs-ha-master.service not found

```

Tried commenting out the dependancy in lizardfs-uraft.service, which allowed it to start, but it never switched to master or assigned the floating ip.

Have installed *all* the 3.13rc1 packages.

Debian 9.5

**Comment by Blackpaw** [comment]
So the lizardfs-ha-master.service is missing from the debian package. I pulled the redhat one from github:

    https://github.com/lizardfs/lizardfs/raw/master/rpm/service-files/lizardfs-ha-master.service

Placing it in /lib/systemd/system and everything now works.

Initial tests, uraft seems quite reliable.

**Comment by mosharaflink** [comment]
Hi Blackpaw,

This issue happens for debian and ubuntu system. For these OS the packages not fully workable. But you can try for CentOS7. I have done successfully with cenots 7 OS. 


Br
Mosharaf

**Comment by Blackpaw** [comment]
Thanks Mosharaf, but I pulled the missing service file from the rpm src on github and got it fully working on debian.

Easy fix and uraft seems very reliable. Like the quota voting system, much less prone to error/split brain than something like keepalived.

**Comment by mosharaflink** [comment]
​​
Dear Blackpaw,



Thank you
​. I also run system now with copy the file from src. However we are
currently running non-ha cluster of lizardfs and planning to migrate in HA.

M
y planning is to shut down all vm and upgrade non-ha to HA and start all
VM.


What you think about the procedure or share share thought for more
safest way of migration.
​?​

​



--

Regards,



*Md Mosharaf Hossain*

Deputy Manager, System & Services

IT Division





Bangladesh Export Import Company Ltd.

Level-9, SAM Tower, Plot #4, Road #22, Gulshan-1, Dhaka-1212, Bangladesh

24X7 Support Lines: 16464, +880 9609 000 121, +880 2 8833300, +880
1819222581
Fax: +880 2 8815747, Email: support@bol-online.com Web: www.bol-online.com



*From:* Blackpaw [mailto:notifications@github.com]
*Sent:* Monday, July 23, 2018 2:53 PM
*To:* lizardfs/lizardfs
*Cc:* Md Mosharaf Hossain; Comment
*Subject:* Re: [lizardfs/lizardfs] lizardfs-ha-master.service missing in
3.13RC1 (#719)



Thanks Mosharaf, but I pulled the missing service file from the rpm src on
github and got it fully working on debian.

Easy fix and uraft seems very reliable. Like the quota voting system, much
less prone to error/split brain than something like keepalived.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/lizardfs/lizardfs/issues/719#issuecomment-406986824>,
or mute the thread

**Comment by Blackpaw** [comment]
Hi Mosharaf, personally I'd be waiting for the full release before upgrading, in the meantime I'm testing with a lab system. 

Are you currently running 3.13RC1, non-ha?

I don't see any harm in activating ha then, though as always, backups are your friend :)

**Comment by mosharaflink** [comment]
Hello Blackpaw,

 

I am running currently lizardfs master with NON-HA and version of 3.12. Now planning to migrate this new HA version of 3.13. 

 

My planning is to shut down all resources running on it and upgrade all NON-HA 3.12 master to 3.13 HA master. After all master/shadow server sync successfully with last metadata version then start all the instances.

 

We want safest migration from 3.12 to 3.13 so that VM data has not risk. Does my procedure is fine or please share anyone thought for more safest way of migration if needed.?​

 

 

 

 

--

Regards,

 

Md Mosharaf Hossain

Deputy Manager, System & Services

IT Division

 

 

Bangladesh Export Import Company Ltd. 

Level-9, SAM Tower, Plot #4, Road #22, Gulshan-1, Dhaka-1212, Bangladesh

24X7 Support Lines: 16464, +880 9609 000 121,  <tel:%2B880%202%208833300> +880 2 8833300,  <tel:%2B880%201819222581> +880 1819222581
Fax:  <tel:%2B880%202%208815747> +880 2 8815747, Email:  <mailto:support@bol-online.com> support@bol-online.com Web:  <http://www.bol-online.com/> www.bol-online.com

**Comment by Zorlin** [comment]
Hi @mosharaflink,

That sounds about right, but I must also warn you that you may be better off waiting for the full release of 3.13. The current version, 3.13rc1 is a *release candidate* and not intended for production usage.

**Comment by foysalkayum** [comment]
@Blackpaw & @Zorlin Thank you for your suggestion. Surely we will wait till the full release of 3.13.0. Mean while we are preparing a test bed with our full stack of cloud infrastructure on the release candidate version and stress test it with possible failure scenarios. Hope to share our experience with the community shortly.
