### ISSUE TITLE
Question: compiling LizardFS 3.13.0-rc1 on Debian Stretch

### ISSUE THREAD

**Issue by tsujp** [lizardfs/lizardfs#811]
I'm having a very hard time trying to compile the latest release on stretch-minimal, can anyone help me out with this? I'm somewhat new to doing all the non-repo packages myself. I am Googling around also, but documentation is sparse (I don't know exactly what I am looking for yet). I've compiled projects from scratch before and this one seems a little harder to me.

**Comment by onlyjob** [comment]
Just build your packages from official Debian repository on Salsa. Branch "experimental" have the latest version. You'll need few patches/corrections for _libspdlog_.

**Comment by pbeza** [comment]
@hito Can you please provide more details how did you try to compile the latest release of LizardFS on `stretch-minimal`? Did you follow [this guideline](https://docs.lizardfs.com/devguide/obtaining.html)?

Note that there was an issue with missing `<sys/sysmacros.h>` header in `src/chunkserver/iostat.h`. This problem was [fixed](https://github.com/lizardfs/lizardfs/commit/5d20c95179be09241b039050bceda3c46980c004) 5 days ago, so let's give it a try once again:

    git clone https://github.com/lizardfs/lizardfs.git
    cd lizardfs/
    mkdir build
    cmake ..
    make
    make install

istead of running plain `cmake ..` you can run `cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/lizardfs` as suggested in [docs](https://docs.lizardfs.com/devguide/obtaining.html).

If you want to compile the project and create `*.deb` packages that you can later install with `sudo apt install package_name.deb` or `dpkg -i package_name.deb` run:

    git clone https://github.com/lizardfs/lizardfs.git
    cd lizardfs/
    ./create-deb-package.sh

**Comment by eleaner** [comment]
I am trying to do a similar thing on docker stretch-slim and I am failing to identify all dependencies to be installed prior running cmake.

is there an easy shortcut for that?

**Comment by pbeza** [comment]
@tsujp @eleaner [This][1] should solve your problem. If you have any specific problem, please describe it and reopen this issue.

[1]: https://github.com/lizardfs/lizardfs/issues/831#issuecomment-511368357
