### ISSUE TITLE
Mounting lizardfs fuse3

### ISSUE THREAD

**Issue by htbase** [lizardfs/lizardfs#822]
Folks

On MooseFS it is possible to mount the storage with the regular "mount -t moosefs" command in Linux

Can we do the same with lizardfs using something like "mount -t lizardfs", now with the fuse3 support?

I understand you can do it with lizardfsmount, but wanted to use the fuse mount command

Thanks!

**Comment by pbeza** [comment]
Currently there is no such an option, but _it will be probably merged very soon_. After merge you will be able to define your shares in `/etc/fstab` as follows:

    lizardfs-master:/ /mnt/lizardfs lzfs default,symlinkcachetimeout=3600 0 0

instead of old-fashioned ([deprecated][1] but still suported for backward compatibility):

    mfsmount /mnt/lizardfs fuse mfssubfolder=/,mfsmaster=lizardfs-master,symlinkcachetimeout=3600 0 0

Live preview:

![Peek 2019-04-29 14-10](https://user-images.githubusercontent.com/3036218/56895208-a4884000-6a88-11e9-8ff4-d8b654ebf222.gif)

What's more you will be able to use mfsmount as follows:

    mfsmount lizardfs-master:9421:/ /mnt/lizardf

Live preview:
![Peek 2019-04-29 14-15](https://user-images.githubusercontent.com/3036218/56895421-650e2380-6a89-11e9-8e35-e5740e316b62.gif)

[1]: https://lwn.net/Articles/221779/
